### ISSUE TITLE
[Forge 1.18.1] Cooking pot > world

### ISSUE THREAD

**Issue by Kiryonn** [vectorwing/FarmersDelight#392] opened 2022-01-20 20:12 UTC
**Description**
when a cooking pot is placed on top of some blocks, the game crash.

**Steps to reproduce:**
place down a cooking pot on the top of sand or sandstone

**Expected behavior:**
i mean ... placing a block to cook i guess ?

**Logs**
crash report sandstone + cooking pot
[crash-2022-01-20_20.56.53-server.txt](https://github.com/vectorwing/FarmersDelight/files/7908159/crash-2022-01-20_20.56.53-server.txt)
crash report sand + cooking pot
[crash-2022-01-20_18.25.01-server.txt](https://github.com/vectorwing/FarmersDelight/files/7908160/crash-2022-01-20_18.25.01-server.txt)

in the latest (sandstone), the logs had way too many lines with `[Render thread/ERROR]: java.lang.ArrayIndexOutOfBoundsException`. Like from 20:56:37 to 20:56:51 it's just spam of this error.
then :
```
[20:56:53] [Server thread/INFO]: Kiryonn has reached the goal [Dinner's Served!]
[20:56:53] [Render thread/INFO]: [CHAT] Kiryonn has reached the goal [Dinner's Served!]
[20:56:53] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:872) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:120) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag vectorwing.farmersdelight.common.block.entity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.writeItems(CookingPotBlockEntity.java:110) ~[FarmersDelight-1.18.1-1.0.2a.jar%2370!/:1.18.1-1.0.2a]
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.m_5995_(CookingPotBlockEntity.java:441) ~[FarmersDelight-1.18.1-1.0.2a.jar%2370!/:1.18.1-1.0.2a]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195642_(ClientboundBlockEntityDataPacket.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.network.protocol.game.ClientboundBlockEntityDataPacket.m_195640_(ClientboundBlockEntityDataPacket.java:25) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at vectorwing.farmersdelight.common.block.entity.SyncedBlockEntity.getUpdatePacket(SyncedBlockEntity.java:26) ~[FarmersDelight-1.18.1-1.0.2a.jar%2370!/:1.18.1-1.0.2a]
	at vectorwing.farmersdelight.common.block.entity.SyncedBlockEntity.m_183216_(SyncedBlockEntity.java:17) ~[FarmersDelight-1.18.1-1.0.2a.jar%2370!/:1.18.1-1.0.2a]
	at net.minecraft.server.level.ChunkHolder.m_140029_(ChunkHolder.java:228) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140032_(ChunkHolder.java:220) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.level.ChunkHolder.m_140054_(ChunkHolder.java:200) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_184021_(ServerChunkCache.java:371) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:370) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_142483_(ServerChunkCache.java:311) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:278) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%2395!/:?]
	... 5 more
``` (sorry i don't have the "5 more" lines

**Screenshots**
no screenshots 😥

**Mod list:**
stated in crash reports

**Comment by vectorwing** [comment] 2022-01-20 20:12
Duplicate of issue #390. **Please** search other issues before posting a new one...

**Closed as completed by vectorwing** 2022-01-20 20:12 UTC
