### ISSUE TITLE
[1.18.2 New Update Breaks World Creation (Datapack Error Screen)

### ISSUE THREAD

**Issue by zachsai** [vectorwing/FarmersDelight#458] opened 2022-04-24 05:54 UTC
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Read Title

**Steps to reproduce:**
Create world with mod?

**Expected behavior:**
World Creates

**Logs**
[Even if the game didn't crash, please submit your client/server logs as well. They contain vital information to troubleshoot the issue.](https://gist.github.com/WelpSTudent/c233a7b2f4ae44f6b19fb16d5f81c3fc)

**Screenshots**
![image](https://user-images.githubusercontent.com/63996164/164958632-5545b8e5-3403-44f9-af1d-933848140808.png)
**Mod list:**
Post a list of your mods here, **Forge and Farmer's Delight versions are mandatory!**
[You can generate a mod list by forcing a crash. In your game, hold F3+C for 10 seconds, then check your logs; the list of mods will be by the end.
](https://pastebin.com/0imDVAsP)
Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment] 2022-04-24 05:56
Duplicate of issue #457. Please search existing issues before opening new ones.

Now, given many folks will be facing this upon updating, I'll leave this one open in the hopes people don't open more. 😓

**Comment by vectorwing** [comment] 2022-04-25 00:39
Seems the author updated! So I'll be closing this issue. 👍

**Closed as completed by vectorwing** 2022-04-25 00:39 UTC
