### ISSUE TITLE
Containers for Cooking recipes should be able to use a tag

### ISSUE THREAD

**Issue by bageldotjpg** [vectorwing/FarmersDelight#312] opened 2021-08-23 02:00 UTC
It would be awesome if the container input for a Cooking Pot recipe could also allow using a tag instead of just an item. I don't see any uses for this in base FD, but it would be a cool thing to support for add-ons and datapacks. 
I think this could be possible by using an Ingredient input instead of an ItemStack - but I know it is probably way less simple than that, I don't have much experience with custom recipes.

*also chances for cutting board, but I think that is already planned*

**Comment by vectorwing** [comment] 2021-10-07 13:28
Perhaps... Back when I first implemented it, I expected container definitions to be absolute, since a given item can only ever have a single container item. Though with the custom container override, that can differ, and items don't necessarily need to give the container back, depending on design (Stuffed Pumpkin, for example).

Another thing that prevented me from doing this was the possibility of allowing players to dump meals *into* the Cooking Pot without cooking; though that idea is essentially scrapped right now.

I'll take a look into it for 0.5, since other recipe changes are already planned. 👍

**Comment by vectorwing** [comment] 2021-10-14 19:54
I just realized this is a duplicate of issue #230... Woops 😅

**Closed as completed by vectorwing** 2021-10-14 19:54 UTC
Labels: enhancement, suggestion
