### ISSUE TITLE
No Fried Egg recipe

### ISSUE THREAD

**Issue by CircusSeal** [vectorwing/FarmersDelight#771] opened 2023-07-13 18:59 UTC
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.2

### Forge version

40.2.4

### Description

I can't get Fried Eggs outside of Creative Mode, so I can't craft Bacon and Eggs (again, without cheating in the eggs). The recipe doesn't accept cooked eggs from other mods either, like Vanilla Food Pantry or Crock Pot.

### Steps to reproduce

Hit R on Fried Egg in JEI.

### Mod list

Mods:
  [✔] abnormals_delight-1.18.2-3.0.2
  [✔] additional_lights-1.18.2-2.1.4
  [✔] appleskin-forge-mc1.18.2-2.4.1
  [✔] AppleTreesRev-Forge-1.18.2-v2.0
  [✘] Aquaculture-1.18.2-2.3.12.jar (disabled)
  [✔] architectury-4.11.93-forge
  [✔] atmospheric-1.18.2-4.0.0
  [✔] AutoRegLib-1.7-53
  [✔] autumnity-1.18.2-3.0.0
  [✔] babyfat-forge-1.18.2-1.1.2
  [✔] balm-3.2.6
  [✔] bendy-lib-forge-2.1.1
  [✔] berry_good-1.18.2-5.0.0
  [✔] bettas_delight_1.2.0_forge_1.18.2
  [✔] bettas-forge-1.18.2-1.1.0
  [✔] BetterDefaultBiomes-1.18.2-Alpha+3.0.0
  [✔] betterspawnercontrol-1.18.2-4.0
  [✔] blueprint-1.18.2-5.5.0
  [✔] boatload-1.18.2-3.0.0
  [✔] buzzier_bees-1.18.2-4.0.0
  [✔] carrotslib-mc1.18.2-4.0
  [✔] cfm-7.0.0-pre35-1.18.2
  [✔] citadel-1.11.3-1.18.2
  [✔] cofh_core-1.18.2-9.2.1.39
  [✔] collective-1.18.2-6.62
  [✔] comforts-forge-1.18.2-5.0.0.6
  [✔] cookielicious-1.18.2-2.4.3
  [✔] create-1.18.2-0.5.1.c
  [✔] create-confectionery1.18.2_v1.0.9
  [✔] creeperconfetti-3.11
  [✔] CrockPot-1.18.2-1.3.1-release
  [✔] cryingportals-1.18.2-2.3
  [✔] culturaldelights-1.18.2-0.14
  [✔] curios-forge-1.18.2-5.0.9.1
  [✔] Decorative+Blocks-forge-1.18.2-2.1.2
  [✔] Decorative+Winter-forge-1.18.2-2.1.0
  [✔] differentiate-1.18.2-1.0.3
  [✔] DoggyTalents-1.18.2-2.5.11
  [✔] enhanced_mushrooms-forge-4.0.1+1.18.2
  [✔] environmental-1.18.2-2.0.0
  [✔] extendedcreativeinventory-1.18.2-2.1
  [✔] extlights-4.4
  [✘] fairylights-5.0.0-1.18.2.jar (disabled)
  [✔] FallingTree-1.18.2-3.5.5
  [✔] FarmersDelight-1.18.2-1.2.2
  [✔] farmingforblockheads-forge-1.18.2-10.0.2
  [✔] followersteleporttoo-1.18.2-2.1
  [✔] furnacerecycle-1.18.2-2.0
  [✔] geckolib-forge-1.18-3.0.57
  [✔] GeneticAnimals-0_8_25
  [✔] gravestone-1.18.2-1.0.2
  [✔] ImmersiveEngineering-1.18.2-8.4.0-161
  [✔] infinitetrading-1.18.2-4.0
  [✔] Jade-1.18.2-forge-5.3.0
  [✔] jei-1.18.2-forge-10.2.1.1005
  [✔] JRFTL+[1.18.1]-1.4.1
  [✔] JustEnoughResources-1.18.2-0.14.1.171
  [✔] kubejs-forge-1802.5.5-build.569
  [✔] Mantle-1.18.2-1.9.45
  [✔] mcw-lights-1.0.6-mc1.18.2forge
  [✔] mobcatcher-1.18.2-4.0.1
  [✔] NaturesCompass-1.18.2-1.9.7-forge
  [✔] neapolitan-1.18.2-3.0.0
  [✔] Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7
  [✔] OptiFine_1.18.2_HD_U_H9
  [✔] Patchouli-1.18.2-71.1
  [✔] peculiars-3.0.0
  [✔] pioneer-1.18.2-1.0.1
  [✔] player-animation-lib-fabric-1.0.2+1.18
  [✔] player-animation-lib-forge-1.0.2+1.18
  [✔] pollen-forge-1.6.1+1.18.2
  [✔] polymorph-forge-1.18.2-0.48
  [✔] projectvibrantjourneys-1.18.2-4.1.1
  [✔] Quark-3.2-358
  [✔] realisticbees-1.18.2-3.3
  [✔] rhino-forge-1802.2.1-build.255
  [✔] seasonals-1.18.2-3.0.0
  [✔] selene-1.18.2-1.17.9
  [✔] shutupexperimentalsettings-1.0.5
  [✔] simplylight-1.18.2-1.4.5-build.43
  [✔] simplytea-1.18.2-2.5.0
  [✔] snowyspirit-1.18.2-1.3.2
  [✔] superflatworldnoslimes-1.18.2-3.0
  [✔] swdm-1.18.2-3.0.1
  [✔] swem-forge-1.18.2-1.2.8
  [✔] TConstruct-1.18.2-3.6.4.113
  [✔] TerraBlender-forge-1.18.2-1.2.0.126
  [✔] u_team_core-1.18.2-4.0.1.259
  [✔] upsizer-mc1.18.2-7.0a1
  [✔] useful_backpacks-1.18.2-1.12.2.94
  [✔] vanillafoodpantry-mc1.18.2-7.0
  [✔] worldedit-mod-7.2.10
  [✔] Xaeros_Minimap_23.5.0_Forge_1.18.2
  [✔] XaerosWorldMap_1.30.6_Forge_1.18.2
  [✔] YungsApi-1.18.2-Forge-2.2.9
  [✔] YungsBetterDungeons-1.18.2-Forge-2.1.0
  [✔] YungsBetterMineshafts-1.18.2-Forge-2.2
  [✔] YungsBetterMineshafts-1.18.2-Forge-2.2(1)
  [✔] YungsExtras-1.18.2-Forge-2.1.0

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment] 2023-07-13 20:10
This is caused by a config in Abnormals Delight, when Environmental is installed. Check the configs, as the add-on seems to disable FD's Fried Egg in favor of its own.

**Comment by CircusSeal** [comment] 2023-07-14 16:26
"
[overrides]
	#Removes and hides Farmer's Delight's ItemGroup and move the items to vanilla ItemGroups
	replaceFDItemGroup = false
"

Should I change this to true? It's the only thing in abnormals_delight-common.toml.

**Comment by vectorwing** [comment] 2023-07-19 02:16
I forgot what was the original cause, but remembered it just now, sorry.

@CircusSeal, this is actually a bug with **Abnormals Delight**. In versions before 1.19, it wrongly disables Fried Egg recipes when Environmental is loaded, instead of Incubation, which is the intended mod.

Please forward this bug to their issues board. It has been fixed on 1.19, but not prior to it.

**Closed as completed by vectorwing** 2023-07-19 02:16 UTC
Labels: unrelated, integration
