### ISSUE TITLE
[1.18.1] [Bug and/or suggestion] Wild crop dimension blacklist

### ISSUE THREAD

**Issue by JaboyKoral** [vectorwing/FarmersDelight#433] opened 2022-03-13 03:01 UTC
**Description**
Wild crops can generate in certain modded End (and Nether, I assume) biomes, such as BYG's Nightshade Forest. I'm guessing it's because those biomes have climate tags that match Farmer's Delight's requirements?

**Expected behavior:**
I assume that crops are only meant to generate in the Overworld, but either way an option to blacklist biomes and dimensions would be helpful.

**Screenshots**
![2022-03-12_21 30 47](https://user-images.githubusercontent.com/4743892/158042448-5f5a9983-c5e7-40be-8b73-e408f5711751.png)

**Comment by vectorwing** [comment] 2022-06-15 19:23
Sorry for the long delay; I've been on a break for a while.

Looking at this on my instance, it seemed weird that they were generating on End Stone, but... apparently, these blocks from BYG are tagged as `forge:dirt`, despite being End Stone. Which means any normal Overworld plant can be planted on it, and Giant Spruce is able to convert it into Podzol, making the End Stone become Dirt.

Part of me feels this is unintended behavior, and might be worth letting the BYG devs know of this. As for a deny-list, I need to check LimonBlaze's PR for it, and see if I should have this on my end for starters, as this is an unusual interaction.

**Comment by vectorwing** [comment] 2022-08-06 22:50
Fixed on commit fae0b24, using new biome tags from forge 40.1.41 and above.
Should be out in the 1.2 release. Thanks to @LimonBlaze for taking the time to help out, though! ❤️

**Closed as completed by vectorwing** 2022-08-06 22:50 UTC
Labels: bug, enhancement
