### ISSUE TITLE
[MC 1.18.2 Forge 40.1.0] Rich soil makes certain parts of blocks untillable with a hoe

### ISSUE THREAD

**Issue by scarfapalooza** [vectorwing/FarmersDelight#535] opened 2022-09-07 13:33 UTC
**Description**
After Organic compost is converted to rich soil, the block in its space that is currently on becomes untillable, even when a new tillable block is placed in the same place as the rich soil.

**Steps to reproduce:**
let the organic compost convert to rich soil then try to till it

**Mod list:**
dynamiclightsreforged-1.18.2_v1.3.3.jar           |Rubidium Dynamic Lights|
		habitat-1.1.3.jar
		Dracovita_Delight_1.0.1_Forge_1.18.2.jar 
		supermartijn642configlib-1.1.6-forge-mc1.18.jar
		beautify-1.18.2-1.4.0.jar
		Nourished Nether Release V14.jar
		Enlightened End RE Release V1.21.jar
		jei-1.18.2-9.7.1.255.jar
		Galosphere-1.18.2-1.0.4.jar
		wildberries-1.0.2.jar
		Architects-Palette-1.18.2-1.2.0.jar
		sophisticatedcore-1.18.2-0.5.9.115.jar		
		rubidium-0.5.3a.jar
		waystones-forge-1.18.2-10.1.0.jar
		Clumps-forge-1.18.2-8.0.0+15.jar
		farmlife-1.18.2-1.0.1.jar
		comforts-forge-1.18.2-5.0.0.4.jar
		YungsApi-1.18.2-Forge-2.0.8.jar
		finsandtails-1.18.2-1.0.1.jar
		sophisticatedbackpacks-1.18.2-3.18.24.704.jar
		twigs-1.1.4-patch4+1.18.2-forge.jar
		bygonenether-1.2.1-1.18.2.jar 
		catalogue-1.6.2-1.18.2.jar		
		balm-3.2.0+0.jar
		vanillacookbook-1.18.2-2.0.0.jar
		twilightforest-1.18.2-4.1.1397-universal.jar
		Silver Birch Release V1.3.jar 
		upgradednetherite-1.18.2-4.2.0.6-release.jar		
		selene-1.18.2-1.17.9.jar 
		supplementaries-1.18.2-1.5.0.jar
		FarmersDelight-1.18.2-1.1.2.jar		
		enhanced_mushrooms-forge-4.0.1+1.18.2.jar
		TerraBlender-forge-1.18.2-1.2.0.126.jar
		pollen-forge-1.5.0+1.18.2.jar
		additionaladditions-4.0.5.jar
		mcw-fences-1.0.6-mc1.18.2.jar
		NethersDelight-1.18.2-2.2.0.jar 
		CNB-1.18.2-1.4.0.jar
		BrewinAndChewin-1.18.2-1.0.1.jar 
		FarmersRespite-1.18.2-1.3.0.jar 
		curios-forge-1.18.2-5.0.7.1.jar
		ecologics-forge-1.18.2-1.7.9.jar 
		oculus-mc1.18.2-1.2.5a.jar
		polymorph-forge-1.18.2-0.44.jar
		AutoRegLib-1.7-53.jar
		Quark-3.2-358.jar
		bettas_delight_1.2.0_forge_1.18.2.jar
		upgradedcore-1.18.2-3.2.0.0-release.jar
		constructionwand-1.18.2-2.7.jar
		Chimes-1.1.2-1.18.2.jar
		Adorn-3.5.0+1.18.2-forge.jar 
		lilwings-forge-1.18.2-1.2.3.jar
		largemeals-1.18.2-1.0.jar
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.4.jar
		mcwfencesbyg-1.18.2-1.3.jar
		windswept-1.18.2-1.0.0.jar 
		sullysmod-1.1.4-beta.jar
blueprint-1.18.2-5.4.7.jar
boatload-1.18.2-3.0.0.jar
buzzier_bees-1.18.2-4.0.0.jar
berry_good-1.18.2-5.0.0.jar
abnormals_delight-1.18.2-3.0.1.jar
bettas-1.18.2-1.0.0.jar
incubation-1.18.2-2.0.2.jar
Delightful-1.18.2-2.0.jar
YungsBetterMineshafts-1.18.2-Forge-2.2.jar 
geckolib-forge-1.18-3.0.37.jar
naturalist-forge-1.1.1-1.18.2.jar
mcw-lights-1.0.4-mc1.18.2.jar

**Comment by vectorwing** [comment] 2022-09-07 16:45
Hey there!

I tried testing this on a minimal instance (just the versions of Farmer's Delight and Forge you're using), and I couldn't replicate what you described. Freshly converted Compost could be tilled normally, as well as tillable blocks placed in its original spot:

![image](https://user-images.githubusercontent.com/5566692/188933752-c444bbf6-1437-4091-9279-3ed50d54989a.png)

This sounds like a rogue interaction with another mod, perhaps one which deals with farmland and hoes. I suggest checking your mods list and disabling a few mods, to see if the issue goes away, or if you can identify a cause.

However, you did help me realize an unintended behavior I skipped: Rich Soil can be tilled despite having a block on top of it. That one I need to get fixed, so thank you! 😅

Please let me know if the suggestion above helps your issue.

**Comment by vectorwing** [comment] 2022-09-23 02:33
The bug I mentioned has been fixed in version 1.2, but I still couldn't replicate the one you described.
Is this still occurring on the new version, @scarfapalooza?

**Comment by vectorwing** [comment] 2023-05-02 13:23
I'll be closing this issue, as it's gotten stale. @scarfapalooza, feel free to reply here if the issue is still occurring, and I'll reopen.

**Closed as completed by vectorwing** 2023-05-02 13:23 UTC
Labels: bug
