### ISSUE TITLE
Knife inverted on the board

### ISSUE THREAD

**Issue by Skrokker** [vectorwing/FarmersDelight#617] opened 2023-01-11 10:21 UTC
The knife on the cutting board seems inverted, the blade is in the air and the handle is stuck in the board.

**Comment by vectorwing** [comment] 2023-01-11 13:03
Duplicate of issue #594. It was a Forge bug, which got recently fixed for 1.19.2 versions.
Please update Forge to version **43.2.3** to fix it. 👍

**Closed as completed by vectorwing** 2023-01-11 13:03 UTC
Labels: duplicate

**Comment by Skrokker** [comment] 2023-01-13 10:02
Thank you very much my friend, good day to you!
