### ISSUE TITLE
Game crashing when open chest

### ISSUE THREAD

**Issue by ItsJac144** [vectorwing/FarmersDelight#769] opened 2023-07-13 14:55 UTC
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1

### Forge version

47.1.3

### Description

in game, every time a chest is opened with an item from farmers delight, the game freezes before crashing entirely. have tried removing your mod and re-adding it but still come across same issue when this mod specifically is installed. if this is an easy fix or something that can be resolved than i would love to know, Thank you.

### Steps to reproduce

opening a chest that has not been opened before.

a chest found in village or in mine shaft specifically.

### Mod list

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\create-1.20.1-0.5.1.d.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\FallingTree-1.20.1-4.1.1.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\just enough items.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\libraryferret-forge-1.20.1-4.0.0.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\sophisticatedbackpacks-1.20.1-3.18.56.890.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\sophisticatedcore-1.20.1-0.5.78.366.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\TerraBlender-forge-1.20.1-3.0.0.167.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\Xaeros_Minimap_23.5.0_Forge_1.20.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\forge-1.20.1-47.1.3-installer.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\FarmersDelight-1.20.1-1.2.2.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\bettervillage-forge-1.20.1-3.1.0.jar"

"C:\Users\jacks\AppData\Roaming\.minecraft\mods\BiomesOPlenty-1.20.1-18.0.0.592.jar"

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment] 2023-07-13 14:56
Duplicate of #762. This has been fixed in hotfix **1.2.2a**; please update to this version. 👍

**Closed as completed by vectorwing** 2023-07-13 14:56 UTC
Labels: duplicate
