### ISSUE TITLE
[1.16.5] Can't add looting to knives

### ISSUE THREAD

**Issue by AdnanuReeves** [vectorwing/FarmersDelight#208] opened 2021-02-26 17:03 UTC
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Been enchanting knives for the last 3 days and trying to add books to them doesn't work, it doesn't show that you can add it in jei either..

**Steps to reproduce:**
Try to enchant or add in anvil, neither works.

**Expected behavior:**
Looting to be able to add on knives in anvils or get it through enchanting.

**Logs**
Even if the game didn't crash, please submit your client/server logs as well. They contain vital information to troubleshoot the issue.

**Screenshots**

**Mod list:**
  [✔️] [1.16.4]+MassInscriber-0.1
  [✔️] abnormals_core-1.16.4-3.0.6
  [✔️] absentbydesign-1.16.5-1.4.1
  [✔️] additional_lights-1.16.4-2.1.3
  [✔️] additionalcolors-1.16.5-1.4.0.1-forge
  [✔️] ae2extras-1.2-1.16.4
  [✔️] aiotbotania-1.16.4-1.7.1
  [✔️] AkashicTome-1.4-16
  [✔️] alexsmobs-1.6.0
  [✔️] allthemodium-1.2.0-1.16.4-35.1.13
  [✔️] Apotheosis-1.16.3-4.4.1
  [✔️] AppleSkin-mc1.16.2-forge-1.0.14
  [✔️] appliedenergistics2-8.3.0-alpha.1
  [✔️] Aquaculture-1.16.5-2.1.16
  [✔️] archers_paradox-1.16.3-1.1.1
  [✔️] architectury-1.8.126-forge
  [✔️] ars_nouveau-1.16.4-1.11.5
  [✔️] astralsorcery-1.16.4-1.13.9
  [✔️] AttributeFix-1.16.5-10.0.1
  [✔️] AutoRegLib-1.6-47
  [✔️] balancedenchanting-1.0
  [✔️] BetterCaves-Forge-1.16.4-1.1.1
  [✔️] BetterDiving-1.16.5-1.2.3
  [✔️] betterendforge-1.16.4-1.5.0
  [✔️] BetterHunger-1.16.5-6.0.1
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.1
  [✔️] BetterThirdPerson-Forge-1.16.4-1.2.0
  [✔️] blockcarpentry-1.16-0.3.5a
  [✔️] BlockDiversity-1.16.5-1.2
  [✔️] BloodMagic-1.16.4-3.1.0-15
  [✔️] Bookshelf-1.16.5-10.0.1
  [✔️] Botania-1.16.4-411
  [✔️] BotaniaAdditionsMC1.16.4-1.0.4
  [✔️] botanical-functioning-flora-1.0.0
  [✔️] botanicalmachinery-1.16.4-0.3.4
  [✔️] BotanyPots-1.16.5-7.0.8
  [✔️] BotanyTrees-1.16.5-3.0.2
  [✔️] buildersaddition-1.16.4-20210214a
  [✔️] buildinggadgets-1.16.5-3.8.0
  [✔️] camera-1.16.5-1.0.5
  [✔️] cartographer-0.0.1-1.16.4-35.1.35
  [✔️] cgm-1.0-1.16.4
  [✔️] champions-forge-1.16.5-2.0.1.4
  [✔️] charm-forge-1.16.5-2.3.2
  [✔️] ChickenChunks-1.16.4-2.7.0.85-universal
  [✔️] chiseled
  [✔️] chiselsandbits-0.2.10-RELEASE
  [✔️] chocolate-1.3.0-1.16.4
  [✔️] citadel-1.6.1
  [✔️] cleancut-mc1.16-2.2-forge
  [✔️] CleanView-1.16.5-v1
  [✔️] ClientTweaks_1.16.3-5.2.0
  [✔️] cloth-config-forge-4.1.3
  [✔️] Clumps-6.0.0.17
  [✔️] CNB-1.16.3_4-1.2.10
  [✔️] cobbler-1.6.1
  [✔️] CodeChickenLib-1.16.4-3.5.1.408-universal
  [✔️] cofh_core-1.16.3-1.1.6
  [✔️] collective-1.16.5-1.67
  [✔️] compactmachines-4.0.0-alpha.8
  [✔️] compactores-1.16.3-3.0.2
  [✔️] compactstorage-1.16.5-5.1b16
  [✔️] configurablebeacons-1.16.2-2.0.1
  [✔️] connectedglass-1.0.6a-mc1.16.4
  [✔️] constructionwand-1.16.2-1.7
  [✔️] Controlling-7.0.0.13
  [✔️] cookiecore-1.16.2-3.0.2-9389769
  [✔️] CookingForBlockheads_1.16.3-9.2.2
  [✔️] corail_pillar-1.16-5.0.0
  [✔️] corail_recycler-1.16-5.0.0
  [✔️] corail_woodcutter-1.16-1.2.1
  [✔️] CosmeticArmorReworked-1.16.5-v1a
  [✔️] CraftingTweaks_1.16.3-12.2.0
  [✔️] create-mc1.16.3_v0.3e
  [✔️] CreativeCore_v2.0.10_mc1.16.4
  [✔️] CrockPot-1.16.3-1.4.0-release
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] Cucumber-1.16.4-4.1.8
  [✔️] culinaryconstruct-forge-1.16.5-4.0.0.6
  [✔️] curios-forge-1.16.5-4.0.4.0
  [✔️] cursedearth-3.1a
  [✔️] customizableelytra-1.16.4-1.2.1
  [✔️] Cyclic-1.16.5-1.1.7
  [✔️] CyclopsCore-1.16.4-1.11.1
  [✔️] dankstorage-3.14
  [✔️] DarkUtilities-1.16.5-8.0.4
  [✔️] decorative_blocks-1.16.4-1.7.2
  [✔️] DefaultOptions_1.16.3-12.2.0
  [✔️] DeLogger-1.16.5-1.0.9+mc-1.16.5
  [✔️] diet-forge-1.16.5-0.7
  [✔️] dimdungeons-1.092-forge-1.16.5
  [✔️] dimensionalpocketsii-1.16.3-0.4.60-beta-universal
  [✔️] Ding-1.16.3-1.2.0
  [✔️] DoggyTalents-1.16.4-2.0.1.3
  [✔️] doomangelring-1.16.4-1.0.0
  [✔️] Druidcraft-1.16.5-0.4.52
  [✔️] DungeonCrawl-1.16.3-2.2.4
  [✔️] dungeons_plus-1.16.4-1.1.3
  [✔️] dynviewdist-1.9
  [✔️] easy_piglins-1.16.5-1.0.0
  [✔️] easy_villagers-1.16.5-1.0.4
  [✔️] effortlessbuilding-1.16.3-2.22
  [✔️] eidolon-0.2.7
  [✔️] elevatorid-1.16.5-1.7.12
  [✔️] embellishcraft-1.16.4-3.3.0.0
  [✔️] EMCB32+1.16.4+v1.1.0
  [✔️] emcbaubles-1.16.3-1.0.0
  [✔️] enchantingbooks-1.1.0
  [✔️] EnchantmentDescriptions-1.16.5-7.0.2
  [✔️] EnderEnhancement-1.16.5-1.1.0.0
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] EnderStorage-1.16.4-2.7.1.166-universal
  [✔️] engineersdecor-1.16.4-1.1.8-b2
  [✔️] engineerstools-1.16.4-1.1.4
  [✔️] ensorcellation-1.16.3-1.1.2
  [✔️] ensorcelled-0.1b
  [✔️] entangled-1.2.11-mc1.16.5
  [✔️] EntityCulling-1.16.5-1.0.0
  [✔️] entitydetectors-1.16.4-1.1.0.1
  [✔️] envirocore-1.16.5-3.0.7.0
  [✔️] enviromats-1.16.5-2.0.7.0
  [✔️] envirotech-1.16.5-3.0.7.0
  [✔️] Exchangers-1.16.5-3.0.2
  [✔️] ExCompressum_1.16.5-4.0.0
  [✔️] exnihilomekanism-1.16-1.0.0.1
  [✔️] exnihilosequentia-1.16-2.0.2.1
  [✔️] exp_ore-1.16.4-1.2
  [✔️] expandedstorage-3.0.5+1.16.3
  [✔️] extendedbonemeal_1.16.5-1.2
  [✔️] extradisks-1.16.4-1.5.0
  [✔️] ExtraStorage-1.16.4-1.3.1
  [✔️] ExtremeReactors2-1.16.4-2.0.23
  [✔️] extremeSoundMuffler-3.7_Forge-1.16.5
  [✔️] eyeofdragons-0.1.0
  [✔️] fakeblocks-1.16.4-1.0.2
  [✔️] FarmersDelight-1.16.3-0.3.2
  [✔️] FarmingForBlockheads_1.16.3-7.2.1
  [✔️] FasterLadderClimbing-1.16.4-0.2.1
  [✔️] FastFurnace-1.16.4-4.4.0
  [✔️] FastWorkbench-1.16.4-4.5.0
  [✔️] ferritecore-2.0.1-forge
  [✔️] findme-1.16.3-2.1.0.0
  [✔️] fixedanvilrepaircost_1.16.5-1.3
  [✔️] flatbedrock-1.16.4-1.1.6
  [✔️] floormats-1.16.5-v1.3.0
  [✔️] FluxNetworks-1.16.5-6.1.6.11
  [✔️] forbidden_arcanus-16.2.0-beta-1
  [✔️] forgeautofish-2.0.3-1.16.x
  [✔️] ForgeEndertech-1.16.4-7.0.10.0-build.0037
  [✔️] FramedBlocks-2.3
  [✔️] framedcompactdrawers-1.16-2.2.0
  [✔️] frozenup-1.0.1
  [✔️] ftb-backups-2.1.1.6
  [✔️] ftb-gui-library-1605.2.1.38-forge
  [✔️] furniture-7.0.0-pre19-1.16.3
  [✔️] gardentools-1.16.4-1.1.0
  [✔️] geckolib-forge-1.16.5-3.0.14
  [✔️] glassential-forge-1.16.4-1.1.5
  [✔️] glazedsymmetry-1.0
  [✔️] GreaterEye-Forge-1.16.5-1.1.12
  [✔️] GunpowderLib-1.16.5-1.2.2
  [✔️] hole_filler_mod-1.2.3
  [✔️] hunterillager-1.16.4-1.2.2
  [✔️] iafgear-1.16.3-1.0.2
  [✔️] iceandfire-2.1.6-1.16.4
  [✔️] ImmersiveEngineering-1.16.5-4.2.1-131
  [✔️] immersiveposts-1.16.3-3.0.0
  [✔️] improved_windows-v1.0.1
  [✔️] industrial-foregoing-1.16.5-3.2.10-09eb824
  [✔️] infinitetrading_1.16.5-1.3
  [✔️] InventoryEssentials_1.16.3-2.3.0
  [✔️] inventorypets-2.0.12
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] inzheFoPCore-v.1.1.0
  [✔️] IronGenerators-1.5.2-final-1.16.x
  [✔️] IronJetpacks-1.16.4-4.2.0
  [✔️] ironshulkerboxes-1.16.4-5.1.11
  [✔️] itemcollectors-1.0.11-mc1.16.5
  [✔️] item-filters-1605.2.4-build.29-forge
  [✔️] itemzoom-1.16.x-2.2.1
  [✔️] JAMD-1.1.9-beta+mc-1.16.5
  [✔️] JAVD-2.5.45+mc-1.16.5
  [✔️] jei-1.16.4-7.6.1.71
  [✔️] jeiintegration_1.16.5-7.0.1.15
  [✔️] JustEnoughCalculation-1.16.5-3.6.4
  [✔️] JustEnoughProfessions-1.16.5-1.2.1
  [✔️] JustEnoughResources-1.16.4-0.12.0.107
  [✔️] Kiwi-1.16.3-3.4.1
  [✔️] Krate-1.16.4-0.1.3
  [✔️] kubejs-1605.3.6-build.168-forge
  [✔️] lanterncolors-1.16.3-2.1.1
  [✔️] LibX-1.16.3-1.0.17
  [✔️] lightestlamp-4.0.7
  [✔️] Lollipop-1.16.4-3.2.7
  [✔️] lootbagmod-1.16.5-1.6.5
  [✔️] LootingBowEnchantment-1.16.3-2.0.0
  [✔️] LostTrinkets-1.16.4-0.1.22
  [✔️] mahoutsukai-1.16.5-v1.28.3
  [✔️] mana-and-artifice-1.3.0.2
  [✔️] managear-1.16.3-2.2.3
  [✔️] manaliquidizer-2.2.0
  [✔️] Mantle-1.16.5-1.6.74
  [✔️] mapperbase-1.16.4-2.3.0.0
  [✔️] MarketCrates-1.16.4-35.1.4-v1.1-universal
  [✔️] mcjtylib-1.16-5.0.16
  [✔️] mcw-bridges-1.0.5-mc1.16.5-4
  [✔️] mcw-doors-1.0.2-mc1.16.5
  [✔️] mcw-furniture-2.0.1-mc1.16.5
  [✔️] mcw-paintings-1.0.0-mc1.16.4-5
  [✔️] mcw-roofs-2.0.1-mc1.16.5-4
  [✔️] mcw-trapdors-1.0.1-mc1.16.5
  [✔️] mcw-windows-1.0.3-mc1.16.5
  [✔️] mdecore-1.16.4-16.1.0
  [✔️] Mekanism-1.16.5-10.0.21.448
  [✔️] MekanismAdditions-1.16.5-10.0.21.448
  [✔️] MekanismGenerators-1.16.5-10.0.21.448
  [✔️] MekanismTools-1.16.5-10.0.21.448
  [✔️] metalbarrels-3.3a
  [✔️] mgui-1.16.4-3.1.3
  [✔️] mightyarchitect-mc1.16.3_v0.5
  [✔️] minecolonies-0.13.643-ALPHA-universal
  [✔️] mobcatcher-3.2
  [✔️] moblocks-v0.8.1b
  [✔️] modnametooltip_1.16.2-1.15.0
  [✔️] modular-routers-1.16.4-7.3.1-50
  [✔️] moreoverlays-1.18.13-mc1.16.5
  [✔️] Morpheus-1.16.4-4.2.68
  [✔️] Morph-o-Tool-1.4-27
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] movingelevators-1.2.33-mc1.16.5
  [✔️] mrplibrary-1.16.5-2.0.0.0-forge
  [✔️] multibeds-1.16-1.7.8
  [✔️] MysticalAdaptations-1.16.4-1.1.1
  [✔️] MysticalAgradditions-1.16.4-4.1.4
  [✔️] MysticalAgriculture-1.16.4-4.1.5
  [✔️] mysticalworld-1.16.4-0.3.1.7
  [✔️] MythicBotany-1.16.3-1.2.5
  [✔️] NaturesCompass-1.16.5-1.8.6
  [✔️] Neat+1.7-27
  [✔️] NetherPortalFix_1.16.3-7.2.1
  [✔️] notenoughcrashes-3.1.6-forge
  [✔️] Notes-1.16.5-1.2.3
  [✔️] obfuscate-0.6.0-1.16.3
  [✔️] observerlib-1.16.4-1.5.1
  [✔️] occultism-1.16.5-1.0.12
  [✔️] Omni-1.16.5-1.2.2
  [✔️] OuterEnd-0.2.8
  [✔️] outvoted-1.16.5-1.1.4
  [✔️] overloadedarmorbar-5.1.0
  [✔️] paintings-1.16.4-7.0.0.1
  [✔️] passiveendermen_1.16.5-1.3
  [✔️] passiveshield_1.16.5-1.1
  [✔️] Patchouli-1.16.4-50
  [✔️] PickleTweaks-1.16.4-5.2.1
  [✔️] pipez-1.16.5-1.0.17
  [✔️] Placebo-1.16.4-4.4.1
  [✔️] plonk-1.16.5-9.0.7
  [✔️] pneumaticcraft-repressurized-1.16.5-2.10.1-140
  [✔️] pocketstorage-1.16.2-0.7.5
  [✔️] polymorph-forge-1.16.4-0.23
  [✔️] portable_stonecutter-1.16.4-1.3.2
  [✔️] potiondescriptions-1.16.3-1.5.0
  [✔️] Powah-1.16.4-2.3.13
  [✔️] practicaltools-1.16.3-1.8
  [✔️] prefab-1.6.4.3
  [✔️] PrettyBeaches_1.16.3-5.2.0
  [✔️] PrettyPipes-1.9.1
  [✔️] preview_OptiFine_1.16.5_HD_U_G7_pre10
  [✔️] ProgressiveBosses-2.2.0-mc1.16.x
  [✔️] ProjectE-1.16.5-PE1.0.0B
  [✔️] ProjectExtended-1.16.5-1.2.0
  [✔️] Psi+1.16-91
  [✔️] psipherals-1.4.0
  [✔️] QuantumStorage-1.16.4-5.3.0
  [✔️] Quark-r2.4-307
  [✔️] quartz-chests-1603.1.0.8
  [✔️] randompatches-2.4.4-forge
  [✔️] rangedpumps-0.8.2
  [✔️] RapidLeafDecay-1.16.5-1.0.0
  [✔️] ratlantis-1.0.0-1.16.3
  [✔️] rats-7.1.1-1.16.5
  [✔️] refinedpipes-0.5
  [✔️] refinedstorage-1.9.12
  [✔️] refinedstorageaddons-0.7.2
  [✔️] relics-0.1.7
  [✔️] reliquary-1.16.3-1.3.4.1061
  [✔️] repurposed_structures-1.16.5-2.4.3
  [✔️] rftoolsbase-1.16-2.0.10
  [✔️] rftoolsbuilder-1.16-3.0.15
  [✔️] rftoolscontrol-1.16-4.0.7
  [✔️] rftoolsdim-1.16-7.0.2-beta
  [✔️] rftoolspower-1.16-3.0.8
  [✔️] rftoolsstorage-1.16-2.0.10
  [✔️] rftoolsutility-1.16-3.0.23
  [✔️] rhino-1.7.13-build.14
  [✔️] rsgauges-1.16.4-1.2.9-b1
  [✔️] RSInfinityBooster-1.16.5-1.0+2
  [✔️] rsrequestify-1.16.3-2.0.1
  [✔️] Runelic-1.16.5-7.0.1
  [✔️] savageandravage-1.16.4-3.0.0
  [✔️] ScalableCatsForce-2.13.4-build-2-with-library
  [✔️] Scannable-MC1.16.4-1.7.3.16
  [✔️] scuba-gear-1.16.5-1.0.2
  [✔️] shetiphiancore-1.16-3.8.5
  [✔️] shulker_enchantments-1.1.1
  [✔️] shulkerbox-1.16.5-1.0.0
  [✔️] ShulkerTooltip-1.9.7
  [✔️] SilentGear-1.16.3-2.6.5+225
  [✔️] SilentLib-1.16.3-4.9.1+64
  [✔️] SilentMechanisms-1.16.3-0.8.10+75
  [✔️] simplemagnets-1.1.1-mc1.16.5
  [✔️] SimpleSponge-1.16.5-5.0.1
  [✔️] SimpleStorageNetwork-1.16.5-1.3.2
  [✔️] simplylight-1.16.4-1.1.2
  [✔️] skinned_lanterns-1.16.4-1.3.1
  [✔️] snad-1.0.5-1.16.5
  [✔️] SneakyMagic-v1.3-1.16.5
  [✔️] SolarFluxReborn-1.16.3-16.2.3
  [✔️] sophisticatedbackpacks-1.16.4-2.2.1.183
  [✔️] SoundFilters-0.14_for_1.16.2
  [✔️] SpartanShields-1.16.4-2.1.1
  [✔️] SpartanWeaponry-1.16.4-2.1.0-beta-3
  [✔️] SpawnerFix-1.16.2-1.0.0.2
  [✔️] Statues-1.16.5-0.1.6.6
  [✔️] storage_overhaul-1.16.5-1.0.1
  [✔️] StorageDrawers-1.16.3-8.2.2
  [✔️] structure_gel-1.16.4-1.7.5
  [✔️] structurize-0.13.139-ALPHA-universal
  [✔️] supermartijn642configlib-1.0.5-mc1.16
  [✔️] supplementaries-1.16.5-0.9.27
  [✔️] sweetconcrete-1.16.5-1.7.1
  [✔️] tablechair.1.16.4-version.1.0
  [✔️] tanknull-2.2a-1.16.4
  [✔️] tesseract-1.0.18-mc1.16.4
  [✔️] TextDamageIndicators-1.16.3-2.0.1
  [✔️] TheAbyss2+1.8.9+1.16.5
  [✔️] theoneprobe-1.16-3.0.7
  [✔️] thermal_cultivation-1.16.3-1.1.6
  [✔️] thermal_expansion-1.16.3-1.1.6
  [✔️] thermal_foundation-1.16.3-1.1.6
  [✔️] thermal_innovation-1.16.3-1.1.7
  [✔️] thermal_locomotion-1.16.3-1.1.6
  [✔️] time-in-a-bottle-1.0.1
  [✔️] titanium-1.16.5-3.2.7
  [✔️] TMechworks-1.16.3+-2.2.3
  [✔️] Toast-Control-1.16.4-4.3.1
  [✔️] tombstone-1.16-6.3.2
  [✔️] tomeofblood-1.16.4-1.0.5
  [✔️] ToolBelt-1.16.3-1.15.2
  [✔️] torcherino-13.0.3+1.16.3
  [✔️] torchmaster-2.3.6
  [✔️] toughnessbar-6.1
  [✔️] towers_of_the_wild-1.16.4-2.0.1
  [✔️] TrampleStopper-2.4.8+mc-1.16.4
  [✔️] trashcans-1.0.7-mc1.16.4
  [✔️] TrashSlot_1.16.3-12.2.1
  [✔️] TravelAnchors-2.3
  [✔️] traverse-1.16.4-0.4.3.8
  [✔️] u_team_core-1.16.4-3.1.17.192
  [✔️] upgrade_aquatic-1.16.5-3.0.1
  [✔️] upsizer-mc1.16.4-6.1.1
  [✔️] vacuumchest-1.0.0-1.16.4
  [✔️] valhelsia_core-16.0.3
  [✔️] valhelsia_structures-16.0.5
  [✔️] valkyrielib-1.16.5-3.0.7.0
  [✔️] VanillaTweaks-1.16.4-1.5.39
  [✔️] veinmining-forge-1.16.5-0.8
  [✔️] Waystones_1.16.3-7.3.1
  [✔️] Wither-Skeleton-Tweaks-1.16.4-5.3.0
  [✔️] woot-1.16.4-1.0.3.2
  [✔️] wormhole-1.1.4-mc1.16.3
  [✔️] Xaeros_Minimap_21.4.0_Forge_1.16.5
  [✔️] XaerosWorldMap_1.12.0.2_Forge_1.16.5
  [✔️] xnet-1.16-3.0.11
  [✔️] XNetGases-1.16.5-2.2.6
  [✔️] xptome-1.16.5-v2.1
  [✔️] YungsApi-1.16.4-Forge-4
  [✔️] zeherlib-1.16.3-1.2.44-universal
  [✔️] ZeroCore2-1.16.4-2.0.21

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment] 2021-02-26 17:33
Testing on a minimal instance with version 0.3.2, the knives are enchantable with Looting.
![image](https://user-images.githubusercontent.com/5566692/109334388-6a805480-783f-11eb-8773-8b238cd94020.png)

I see you have some mods that also introduce knives, such as Aquaculture. Make sure you're actually trying to enchant a knife from FD (they have a curved blade edge). If you are, some other mod might be interfering with enchantments.

**Comment by AdnanuReeves** [comment] 2021-02-26 18:02
Damn.. I'm not sure what is causing it then because I have made sure I'm using the farmer's delight knives :(

**Comment by vectorwing** [comment] 2021-02-26 22:33
Your modlist is rather large, so testing one by one might not be feasible. Still, try making a minimal instance and re-adding the mods in batches to see if the issue goes away and/or is caused by something in there.

Are you playing on a premade modpack, or is it a custom instance?

**Comment by AdnanuReeves** [comment] 2021-02-27 08:48
It's a custom pack I made, and yeah there's a lot of mods so it'd be a pain to try and track it down :/ Tbh I guess I'll just try to enchant it with the command. (that didn't work lol)
Sorry for taking your time. Thanks for the responses :) I really love your mod, keep up the great work!

**Comment by vectorwing** [comment] 2021-03-13 02:56
What you could do to troubleshoot more easily is do a "binary search":

- Remove half of all mods except FD and try enchanting again:
  - Did the problem persist? Cut the mod list in half again until it goes away;
  - Did the problem go away? One of the removed mods is the culprit; try sifting the ones you removed.

Unfortunately, I could not replicate the issue on my own end, sorry. I'll close the issue for the time being, but feel free to post/reopen if you manage to detect something new!

**Closed as completed by vectorwing** 2021-03-13 02:56 UTC
