### ISSUE TITLE
[1.16.5] Tinker's Tools Broken Tools Work Cutting Board

### ISSUE THREAD

**Issue by hotdog95** [vectorwing/FarmersDelight#278] opened 2021-06-08 09:55 UTC
**Description**
Using a tinker's construct axe on the cutting board will work, and the durability is decreased per use, however once the tool is broken it can still be used for the recipes.

**Mod list:**
Farmer's Delight v0.4.3
Tinker's Construct v3.0.4.171
Forge v36.1.25

**Comment by vectorwing** [comment] 2021-06-08 14:00
If the broken version of the tool still contains the `axe` ToolType, it will still be capable of operating the Cutting Board. Looking at their code, it does seem they made a broken tool lose its types, so this is a bit odd.

Not sure if there's much I can do on my end, but if their tools should *not* have a tool type when broken, it might be worth opening the issue on their board as well. I'll keep this one open to follow any updates, and to see whether changes are needed on my end 👍

**Comment by vectorwing** [comment] 2021-10-15 01:49
After running some tests, I think I figured out the problem.
(technical mumbo jumbo incoming)

There's nothing wrong with Tinker's tools: they assign and lose their ToolType correctly. The problem is how FD initializes ToolIngredient.

A Tinker's "modular axe" (`tconstruct:hand_axe`), is registered with a ToolType.AXE. A Tetra modular tool isn't (`tetra:modular_double`). When a ToolIngredient is created, it scans all registered items that have that ToolType, so JEI can display them. The problem is that I'm **also** checking this list, when I should be checking the given tool's ToolTypes instead. The result is that it always returns true for Tinker's tools, no matter what.

I'll need to run some tests over this, but the fix seems clear. Sorry for taking this long to test it. 👍

**Comment by vectorwing** [comment] 2021-10-15 02:10
Fixed on commit 0c2b5ea, will be released on version 0.5. Thanks for the help!

**Closed as completed by vectorwing** 2021-10-15 02:10 UTC
Labels: bug
