### ISSUE TITLE
[1.18] Crash on adding rice to world (?)

### ISSUE THREAD

**Issue by Quillwerth** [vectorwing/FarmersDelight#380] opened 2022-01-14 01:29 UTC
**Description**
Server crash, which the client reported as a StackOverflowException. Server was able to save after both crashes. Removing Farmer's Delight has made crashes go away. Crash happened twice, I've included both traces below.

**Steps to reproduce:**
Uncertain - I think it was occurring when a new chunk was being generated.

**Expected behavior:**
Don't crash :)

**Logs**

*Log 1:*
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/12/22, 10:32 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: DIRT
	at vectorwing.farmersdelight.common.item.RiceItem.m_6225_(RiceItem.java:27) ~[FarmersDelight-1.18.1-1.0.1.jar%2345!:1.18.1-1.0.1] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:583) ~[forge-1.18.1-39.0.19-universal.jar%2361!:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.4.0-91-generic
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1175031248 bytes (1120 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7371 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 2
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129942.16
	Virtual memory used (MB): 63241.34
	Swap memory total (MB): 1023.99
	Swap memory used (MB): 147.23
	JVM Flags: 2 total; -Xmx4096M -Xms2048M
	Server Running: true
	Player Count: 6 / 10; [ServerPlayer['Quillwerth'/553, l='ServerLevel[world]', x=214.70, y=53.00, z=169.70], ServerPlayer['ceephalopod'/2704, l='ServerLevel[world]', x=173.66, y=64.00, z=72.30], ServerPlayer['SecondFifth'/1232, l='ServerLevel[world]', x=397.92, y=60.88, z=471.08], ServerPlayer['sparrow8771'/2000, l='ServerLevel[world]', x=233.66, y=62.00, z=129.38], ServerPlayer['kazoo_ya'/47138, l='ServerLevel[world]', x=-4.32, y=68.00, z=16.62], ServerPlayer['howlcore'/5217, l='ServerLevel[world]', x=25.46, y=111.25, z=-480.93]]
	Data Packs: vanilla, mod:farmersdelight, mod:decorative_blocks, mod:repurposed_structures, mod:terrablender, mod:biomesoplenty, mod:jade, mod:jeed (incompatible), mod:jei (incompatible), mod:crafttweaker (incompatible), mod:forge, mod:decorative_winter, mod:flywheel, mod:supplementaries (incompatible), mod:create, mod:step (incompatible), mod:selene (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.1.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.18.1-2.0.2.jar          |Decorative Blocks             |decorative_blocks             |2.0.2               |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-4.1.0+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.1.0+1.18.1        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.40.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.40     |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.1-15.0.0.95-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.95    |DONE      |Manifest: NOSIGNATURE
		Jade-1.18-4.1.1.jar                               |Jade                          |jade                          |4.1.1               |DONE      |Manifest: NOSIGNATURE
		jeed-1.18-1.6.jar                                 |Just Enough Effect Description|jeed                          |1.18-1.6            |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.1-9.0.0+18.jar            |CraftTweaker                  |crafttweaker                  |9.0.0+18            |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.19-universal.jar                |Forge                         |forge                         |39.0.19             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Decorative Winter-forge-1.18.1-2.0.0.jar          |Decorative Winter             |decorative_winter             |2.0.0               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.1.8.jar                  |Supplementaries               |supplementaries               |1.1.7               |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		step-1.18-1.1.0.jar                               |Step                          |step                          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.11.jar                              |Selene                        |selene                        |1.18-1.11.0         |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.16.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.16.0              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: b4dc8735-d112-4d1e-a719-c22ee09f0340
	FML: 39.0
	Forge: net.minecraftforge:39.0.19
```

*Log 2*:
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 1/12/22, 10:39 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: DIRT
	at vectorwing.farmersdelight.common.item.RiceItem.m_6225_(RiceItem.java:27) ~[FarmersDelight-1.18.1-1.0.1.jar%2345!:1.18.1-1.0.1] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:583) ~[forge-1.18.1-39.0.19-universal.jar%2361!:?] {re:classloading}
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:computing_frames,re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:110) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:727) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2357!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 5.4.0-91-generic
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2330273632 bytes (2222 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD EPYC 7371 16-Core Processor
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 2
	Microarchitecture: Zen
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 32
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 129942.16
	Virtual memory used (MB): 51795.59
	Swap memory total (MB): 1023.99
	Swap memory used (MB): 79.56
	JVM Flags: 2 total; -Xmx4096M -Xms2048M
	Server Running: true
	Player Count: 5 / 10; [ServerPlayer['howlcore'/230, l='ServerLevel[world]', x=-220.30, y=-37.92, z=350.23], ServerPlayer['Quillwerth'/463, l='ServerLevel[world]', x=238.40, y=50.00, z=133.58], ServerPlayer['kazoo_ya'/1505, l='ServerLevel[world]', x=123.35, y=66.00, z=15.69], ServerPlayer['SecondFifth'/2384, l='ServerLevel[world]', x=315.94, y=64.00, z=442.43], ServerPlayer['sparrow8771'/4179, l='ServerLevel[world]', x=233.66, y=62.00, z=129.38]]
	Data Packs: vanilla, mod:farmersdelight, mod:decorative_blocks, mod:repurposed_structures, mod:terrablender, mod:biomesoplenty, mod:jade, mod:jeed (incompatible), mod:jei (incompatible), mod:crafttweaker (incompatible), mod:forge, mod:decorative_winter, mod:flywheel, mod:supplementaries (incompatible), mod:create, mod:step (incompatible), mod:selene (incompatible), mod:citadel, mod:alexsmobs (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.0.7+91+master.8569cdf
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		server-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.1.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.18.1-2.0.2.jar          |Decorative Blocks             |decorative_blocks             |2.0.2               |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-4.1.0+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.1.0+1.18.1        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.1-1.1.0.40.jar            |TerraBlender                  |terrablender                  |1.18.1-1.1.0.40     |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.1-15.0.0.95-universal.jar      |Biomes O' Plenty              |biomesoplenty                 |1.18.1-15.0.0.95    |DONE      |Manifest: NOSIGNATURE
		Jade-1.18-4.1.1.jar                               |Jade                          |jade                          |4.1.1               |DONE      |Manifest: NOSIGNATURE
		jeed-1.18-1.6.jar                                 |Just Enough Effect Description|jeed                          |1.18-1.6            |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.1-9.0.0+18.jar            |CraftTweaker                  |crafttweaker                  |9.0.0+18            |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.19-universal.jar                |Forge                         |forge                         |39.0.19             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Decorative Winter-forge-1.18.1-2.0.0.jar          |Decorative Winter             |decorative_winter             |2.0.0               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.1.8.jar                  |Supplementaries               |supplementaries               |1.1.7               |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		step-1.18-1.1.0.jar                               |Step                          |step                          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.11.jar                              |Selene                        |selene                        |1.18-1.11.0         |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.16.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.16.0              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 3614e408-7901-4695-b00c-b51c1887d2d8
	FML: 39.0
	Forge: net.minecraftforge:39.0.19
```

**Mod list:**
(Included above)

**Comment by MythrilBagels** [comment] 2022-01-14 01:33
A common issue that's popped up a few times. Forge apparently removed its "Dirt" tag in the recent updates

**Comment by Quillwerth** [comment] 2022-01-14 01:33
I assume no fix as-of-yet?

**Comment by vectorwing** [comment] 2022-01-14 01:34
Duplicate of issue #379. Downgrade your Forge version to 39.0.17 for now.

**Closed as completed by vectorwing** 2022-01-14 01:34 UTC
Labels: duplicate
