### ISSUE TITLE
[1.16.5] Java 15 Causes Crash on Launch

### ISSUE THREAD

**Issue by SaltSouls** [vectorwing/FarmersDelight#225] opened 2021-03-13 20:11 UTC
After installing Java 15 and launching the mod, it crashes upon launch giving me
```
Failure message: Farmer's Delight (farmersdelight) has failed to load correctly
		java.lang.IllegalStateException: Failed to resolve consumer event type: vectorwing.farmersdelight.FarmersDelight$$Lambda$3950/0x0000000075c8e500@f3d4086a
```
[Log File](https://haste.zneix.eu/unitizuwej.rb)

**Comment by vectorwing** [comment] 2021-03-13 20:19
This is a duplicate of issue #190, and it happens because you're using the OpenJ9 virtual machine. Follow the other issue's details for updates. 👍

**Closed as completed by vectorwing** 2021-03-13 20:19 UTC
Labels: duplicate

**Comment by SaltSouls** [comment] 2021-03-13 20:20
> This is a duplicate of issue #190, and it happens because you're using the OpenJ9 virtual machine.
> #190

Is there any plan to fix/support this for the people that are using it?

**Comment by vectorwing** [comment] 2021-03-13 20:21
As stated above, things are being looked into, and details are posted on the linked issue.
