### ISSUE TITLE
[MC Version]: 1.19.2

### ISSUE THREAD

**Issue by NimbusWSW** [vectorwing/FarmersDelight#621] opened 2023-01-26 12:52 UTC
### Description

Knife items not recognized as knife tools. Cannot perform knife-unique interactions such as harvesting straw from wheat/rice/tall grass, or cutting board recipes involving knives. 

From JEI Recipes: "Empty Tag: forge:tools/knives" when hovering over knife item in JEI Recipe page. Additionally, the knife item in the recipe is replaced with a red null symbol, and displaying uses for knives in JEI will not show any cutting board recipes.

### Steps to reproduce

1. Open inventory
2. Search for any item with a cutting board recipe that uses knives
3. Open the item's recipe page on JEI
4. Optionally: Attempt to use any of the knife's unique scavenging interactions using a knife from either Farmer's Delight or Delightful.

### Mod list

Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-1.19.2_v1.4.0.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.19.2_v1.4.0       |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.19.2-Forge-3.2.2.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.2  |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.1.31-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.1.31       |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.19.2-9.1.0-156.jar         |Immersive Engineering         |immersiveengineering          |1.19.2-9.1.0-156    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		jei-1.19.2-forge-11.5.2.1007.jar                  |Just Enough Items             |jei                           |11.5.2.1007         |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.11.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.11.0+1.19         |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		rubidium-0.6.2.jar                                |Rubidium                      |rubidium                      |0.6.2               |DONE      |Manifest: NOSIGNATURE
		immersive_weathering-1.19.2-1.2.5-forge.jar       |Immersive Weathering          |immersive_weathering          |1.19.2-1.2.5        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.h.jar                         |Create                        |create                        |0.5.0.h             |DONE      |Manifest: NOSIGNATURE
		createdeco-1.2.12-1.19.2.jar                      |Create Deco                   |createdeco                    |1.2.12-1.19.2       |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.19.2-1.2.8a.jar                        |Oculus                        |oculus                        |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.46.1+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.1+1.19.2       |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.19.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.2.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.2  |DONE      |Manifest: NOSIGNATURE
		nocube's_farmers_compats_1.0.0_Forge_1.19.2.jar   |Farmer's Compats (by NoCube)  |nocubes_farmer_compats        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.19.2-3.0.0.jar          |Decorative Blocks             |decorative_blocks             |3.0.0               |DONE      |Manifest: NOSIGNATURE
		effective_fg-1.3.4.jar                            |Effective (Forge)             |effective_fg                  |1.3.4               |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		everycomp-1.19.2-2.2.3.jar                        |Every Compat                  |everycomp                     |1.19.2-2.2.3        |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.1  |DONE      |Manifest: NOSIGNATURE
		architectury-6.4.62-forge.jar                     |Architectury                  |architectury                  |6.4.62              |DONE      |Manifest: NOSIGNATURE
		createchunkloading-1.3.0-forge.jar                |Create Chunkloading           |createchunkloading            |1.3.0               |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		blueprint-1.19.2-6.1.0.jar                        |Blueprint                     |blueprint                     |6.1.0               |DONE      |Manifest: NOSIGNATURE
		personality-1.19-3.0.1.jar                        |Personality                   |personality                   |3.0.1               |DONE      |Manifest: NOSIGNATURE
		rubidium_extras-1.19.2_v1.3.2.jar                 |Rubidium Extras               |rubidium_extras               |1.19.2_v1.3.2       |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quark-3.4-388.jar                                 |Quark                         |quark                         |3.4-388             |DONE      |Manifest: NOSIGNATURE
		Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        |Towns and Towers              |t_and_t                       |1.10                |DONE      |Manifest: NOSIGNATURE
		Delightful-1.19-3.2.1.jar                         |Delightful                    |delightful                    |3.2.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.2.43.jar                 |Supplementaries               |supplementaries               |1.19.2-2.2.43       |DONE      |Manifest: NOSIGNATURE
		createaddition-1.19.2-20221230a.jar               |Create Crafts & Additions     |createaddition                |1.19.2-20221230a    |DONE      |Manifest: NOSIGNATURE
		createplus-1.19.2_v0.5.2a.jar                     |Create Plus                   |createplus                    |1.19.2_v0.5.2a      |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: Off
	Crash Report UUID: 732fe3f9-ccf1-4e8c-8b7a-724964fefeea
	FML: 43.2
	Forge: net.minecraftforge:43.2.0

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by Lethosos** [comment] 2023-01-26 19:40
The error is usually caused by a malformed forge tag JSON that attempts to append/replace the existing tag in FD (which is actually correct.)

I've seen this with Farmers Compat before, so it's worth looking at any mod/datapack that attempts to do the same.

**Comment by NimbusWSW** [comment] 2023-01-27 03:32
Oh yeah, removing Farmers Compat seems to fix it. Thanks for that.

**Comment by vectorwing** [comment] 2023-05-01 01:00
Duplicate of #620 and a few others. Caused by Farmer's Compats, disable it to fix. 👍

**Closed as completed by vectorwing** 2023-05-01 01:00 UTC
Labels: duplicate
