### ISSUE TITLE
Interacting with basket crashes the game with Dungeons Gear installed

### ISSUE THREAD

**Issue by Milinko1** [vectorwing/FarmersDelight#790] opened 2023-08-05 18:42 UTC
as title says
 Dungeons gear mod https://legacy.curseforge.com/minecraft/mc-mods/dungeons-gear
 Any type of interaction cause the game to crash for tickloop

**Comment by DRockLee** [comment] 2023-08-06 02:04
Getting the same issue, posting a crashlog as well. Also want to add it's not just interactioning, you can crash if you load a chunk with a dungeons gear in a basket (like, say, if you use a modpack with custom loot tables).
[crash-2023-08-05_18.57.17-server.txt](https://github.com/vectorwing/FarmersDelight/files/12268559/crash-2023-08-05_18.57.17-server.txt)

**Comment by vectorwing** [comment] 2023-08-06 03:43
Duplicate of #714.

The Basket copies the implementation for loot gen from the Hopper, so the issue seems to be on Dungeons Gear's end. Not sure if any updates have been released yet.

**Closed as completed by vectorwing** 2023-08-06 03:43 UTC
