### ISSUE TITLE
[1.16.4] Incompatibility issue

### ISSUE THREAD

**Issue by JavierMusso** [vectorwing/FarmersDelight#103] opened 2020-12-14 16:37 UTC
Hi, I have an issue when Farmer's Delight and Goo. When both are installed, all items say 'can't gooify', and the machine won't gooify. I have submitted this to Goo's discord already, but just in case will submit it here too.

It is easily replicable, just install both mods, it's relatives, and try to use de Gooifier.

An expected behavior would be that the gooifier works, smelting the things you put on it.

Mod list:
[Goo](https://www.curseforge.com/minecraft/mc-mods/goo)
[Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)

Thanks!

**Comment by vectorwing** [comment] 2020-12-14 16:44
Hello! This is a duplicate of issue #95. Nothing I can do on my end except remove salvaging recipes; the Aequivaleo devs are aware of the issue and are looking for a fix.

**Closed as completed by vectorwing** 2020-12-14 16:44 UTC
