### ISSUE TITLE
[1.18.2] : Unknown type: vectorwing.farmersdelight.common.loot.function.CopySkilletFunction

### ISSUE THREAD

**Issue by kaelianbaudelet** [vectorwing/FarmersDelight#739] opened 2023-06-20 15:40 UTC
### Description

Farmer Delight prevents the creation of a minecraft world and access to a world, I know what causes the problem but I do not see how to fix it knowing that I do not want to uninstall any mod, it is what I saw a problem reading a json file, it is impossible for a focntione to retrieve a certain value. As a developer myself, I'm convinced it's just a small value to be changed in one of the mixins/jsons files.

After checking, I found that the problem came from [RER](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources). When I deinstalled REI and its extensions, everything worked fine, but you can understand that I don't want to part with REI and its extensions, and I wanted to see how to solve the problem between your mod and REI and REI extension particulary on RER (responsible of world error creation/access).

It would be appreciated if a future update could include a validator or assert to avoid these problems in different mod functions or add a compat with REI, RER, REP, REIPC and JEED.

```[20Jun2023 17:06:21.980] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
com.google.gson.JsonSyntaxException: Unknown type: vectorwing.farmersdelight.common.loot.function.CopySkilletFunction@53f5445d```
```
![image](https://github.com/vectorwing/FarmersDelight/assets/44731817/b5f0e87a-7092-47e2-adb1-9d9ecd0b28b3)

### Steps to reproduce

1. Install all my modlist and add FarmerDelight (With CurseForge App)
2. Launch Minecraft Instance
3. Creating and accessing a new world

### Mod list

- 3DSkinLayer
- Accurate Block Placement
- Advanced Compass
- Advancement Plaques
- Advancements Tracker
- Alex's Mobs
- Ambiant Sound
- Animalistic
- AntiGhost
- Apple Skin
- Architectury (Lib/API)
- Artifacts
- AtributesFix
- AutoRegLIb
- Auudio
- Balm
- Better Advancements
- Better Biome Blend
- Better Brightness Slider
- Better Rubiduim Video Setting
- Better F3
- Blueprint
- Canary
- Cataclysm Mod
- Catalogue
- Chat Heads
- Citadel
- ClearDespawn
- Client Tweaks
- Cloth Config v4 API
- Clumps
- ColaConfig
- Configurated
- ConnectedTextureMod
- Connectivity Mod
- Controlling
- Corpse
- Create
- Create : Encased
- Create Confectionnary
- Create Crafts & Additions
- Create Deco
- Create Deco Casing
- Create Enchantement Industry
- Create Ender Transmition
- Create Jetpack
- Create Liquid Fuel
- Create Recycling
- Create Stuff & Addition
- Create : Chromatic Return
- Create Factory
- CreativeCore
- CristelLib
- CuriosAPI
- Cyclops Core
- Delogger
- Do a Barrel Roll
- Dripply Loading Screen
- Droplight
- Dynamic Crosshair
- Eating Animation
- Effective [Forge]
- EntityCulling
- ExpandAbility
- Falling Leaves
- FancyMenu
- FancyMenu Audio Extension
- Farmer Delight 💣
- Farsight mod
- Fast Entity Transfer
- Fastload
- FlightLib
- Flywheel
- Fog Looks Good Now
- GeckoLib
- Framework API
- GottschCore
- IKWID
- Iceberg
- Illuminations
- InvMode
- InvModeCompat
- Item Borders
- Jade
- Jade Addons
- Journeymap
- JumpOverFence
- JEED
- Konkrete
- Kotlin for Forge
- legendary Tooltips
- Library ferret
- Lightspeed
- Load my ressources
- Mantle
- Mouse Tweaks
- No Telemetry
- NochatLagForge
- Not Enough Crashes
- Oculus
- Oculus Flywheel Compat
- Optifine Capes
- Patchouli
- Placebo
- Pluto
- Pop!
- Prism
- Puzzle Lib
- REI Plugin Compat
- Replanter
- REI
- REP
- RER
- Rubidium
- Rubidium Extra
- Saturn
- Screenshot to clipboard
- Seaborgium
- Selene
- SmoothBoot (Reloaded)
- Starlight
- Tiny Item Animations
- Toast Control
- Torch hit!
- Transparent
- WAILA (Jade)
- WaveyCapes Mod
- XL Packets
- Yungs API
- Cat_Jam

### Logs

Logs at the world creation to the error :

```
...
[20Jun2023 17:05:55.240] [Server thread/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[20Jun2023 17:05:55.240] [Thread-0/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[20Jun2023 17:05:55.240] [Thread-0/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[20Jun2023 17:05:55.248] [Thread-0/INFO] [journeymap/]: Loading JourneyMap Forge Configs
[20Jun2023 17:05:55.413] [Server thread/INFO] [configured/]: Loading server configs...
[20Jun2023 17:06:00.919] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Preparing start region for dimension minecraft:overworld
[20Jun2023 17:06:20.197] [Server thread/INFO] [net.minecraftforge.server.permission.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
[20Jun2023 17:06:20.208] [Server thread/INFO] [org.forsteri.createliquidfuel.CreateLiquidFuel/]: HELLO from server starting
[20Jun2023 17:06:20.213] [Render thread/INFO] [net.minecraft.server.level.progress.LoggerChunkProgressListener/]: Time elapsed: 92078 ms
[20Jun2023 17:06:20.223] [Server thread/INFO] [net.forsteri.createendertransmission.CreateEnderTransmission/]: HELLO from server starting
[20Jun2023 17:06:20.224] [Server thread/INFO] [patchouli/]: Sending reload packet to clients
[20Jun2023 17:06:20.465] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing view distance to 12, from 10
[20Jun2023 17:06:20.467] [Server thread/INFO] [net.minecraft.client.server.IntegratedServer/]: Changing simulation distance to 12, from 0
[20Jun2023 17:06:21.350] [Server thread/INFO] [com.github.alexthe666.alexsmobs.AlexsMobs/]: Found Pupfish chunk at 399 ~ -1184 after 13 tries
[20Jun2023 17:06:21.671] [Netty Local Client IO #0/INFO] [net.minecraftforge.network.NetworkHooks/]: Connected to a modded server.
[20Jun2023 17:06:21.704] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@3b73296c
[20Jun2023 17:06:21.722] [Server thread/INFO] [net.minecraft.server.players.PlayerList/]: Afi_[local:E:f3aa44c9] logged in with entity id 351 at (-3.5, 75.0, 4.5)
[20Jun2023 17:06:21.774] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Afi_ joined the game
[20Jun2023 17:06:21.810] [Render thread/INFO] [Advancements Tracker/]: Widget will be automatically visible on the start.
[20Jun2023 17:06:21.810] [Render thread/INFO] [Advancements Tracker/]: Set widget size to 135x0
[20Jun2023 17:06:21.810] [Render thread/INFO] [Advancements Tracker/]: Set widget base position to: MIDDLE_RIGHT
[20Jun2023 17:06:21.810] [Render thread/INFO] [Advancements Tracker/]: Set widget position top offset 0 and left offset 0
[20Jun2023 17:06:21.811] [Render thread/INFO] [Advancements Tracker/]: Preparing tracked advancements ...
[20Jun2023 17:06:21.811] [Render thread/INFO] [Advancements Tracker/]: Loading default (config) tracked advancements: []
[20Jun2023 17:06:21.811] [Render thread/INFO] [Advancements Tracker/]: Loading local (user) tracked advancements: []
[20Jun2023 17:06:21.882] [Render thread/INFO] [BatchExecutor/]: Started 6 worker threads
[20Jun2023 17:06:21.897] [Server thread/INFO] [Waila/]: Syncing config to Afi_ (6a9ce7f2-809f-4bc6-b8cb-7f88df63a82c)
[20Jun2023 17:06:21.980] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
com.google.gson.JsonSyntaxException: Unknown type: vectorwing.farmersdelight.common.loot.function.CopySkilletFunction@53f5445d
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:120) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2336!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_7219_(LootPoolSingletonContainer.java:141) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:43) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:80) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2336!/:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:187) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2336!/:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:278) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:252) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2336!/:?]
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2336!/:?]
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53) ~[rer-2.5.2.jar%23163!/:?]
	at net.minecraft.server.players.PlayerList.handler$zeg000$onPlayerConnect(PlayerList.java:910) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:239) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23182!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20Jun2023 17:06:22.029] [Render thread/INFO] [ChunkBuilder/]: Started 6 worker threads
[20Jun2023 17:06:22.031] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Afi_ lost connection: Invalid player data
[20Jun2023 17:06:22.031] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Afi_ left the game
[20Jun2023 17:06:22.069] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Stopping singleplayer server as player logged out
[20Jun2023 17:06:22.070] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[20Jun2023 17:06:22.070] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[20Jun2023 17:06:22.070] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[20Jun2023 17:06:22.408] [Render thread/INFO] [dev.tr7zw.skinlayers.donor.DonorSkinProvider/]: Animated skins loaded and ready to use!
[20Jun2023 17:06:22.631] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[kkkkkkkk]'/minecraft:overworld
[20Jun2023 17:06:27.751] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[kkkkkkkk]'/minecraft:the_end
[20Jun2023 17:06:27.754] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[kkkkkkkk]'/minecraft:the_nether
[20Jun2023 17:06:27.841] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (kkkkkkkk): All chunks are saved
[20Jun2023 17:06:27.841] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20Jun2023 17:06:27.841] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20Jun2023 17:06:27.841] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[20Jun2023 17:06:29.822] [Server thread/INFO] [configured/]: Unloading server configs...
[20Jun2023 17:06:29.862] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[20Jun2023 17:06:29.863] [Render thread/WARN] [Seaborgium/]: Shader cache needs invalidated. Reason: Title Screen Created.
[20Jun2023 17:06:29.863] [Render thread/WARN] [Seaborgium/]: Shader cache invalidated!
```

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment] 2023-06-23 22:39
Duplicate of #565. This is a bug on FD's end; I left the loot function type null when it shouldn't be, which breaks RER loading.

Fixed on commit 6591911, should be out later for 1.18, 1.19 and 1.20. 👍

**Closed as completed by vectorwing** 2023-06-23 22:39 UTC
Labels: bug, duplicate
