### ISSUE TITLE
[MC Version]: roughly enough resources issue (again)

### ISSUE THREAD

**Issue by MCBEModder2020** [vectorwing/FarmersDelight#645] opened 2023-02-21 23:30 UTC
### Description

when entering a world in singleplayer, it kicks the player for invalid player data

### Steps to reproduce

create world
join
get error message

### Mod list

```
-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (aarch64) version 13.1
	Java Version: 17.0.4.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Eclipse Adoptium
	Memory: 2923709144 bytes (2788 MiB) / 4433379328 bytes (4228 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 8
	Processor Vendor: Apple Inc.
	Processor Name: Apple M1
	Identifier: Apple Inc. Family 0x1b588bb3 Model 0 Stepping 0
	Microarchitecture: ARM64 SoC: Firestorm + Icestorm
	Frequency (GHz): 24.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: Apple M1
	Graphics card #0 vendor: Apple (0x106b)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 0.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: unknown
	Virtual memory max (MB): 21504.00
	Virtual memory used (MB): 16100.28
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 3683.81
	JVM Flags: 2 total; -Xms512m -Xmx8192m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Apple M1 GL version 4.1 Metal - 83, Apple
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: version: Metal
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, file/create_brbclean
	Current Language: English (US)
	CPU: 8x Apple M1
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		dynamiclightsreforged-1.18.2_v1.3.3.jar           |Rubidium Dynamic Lights       |dynamiclightsreforged         |1.18.2_v1.3.3       |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughProfessions-forge-1.18.2-1.0.2.jar   |Roughly Enough Professions    |roughlyenoughprofessions      |1.0.2               |DONE      |Manifest: NOSIGNATURE
		AdvancedPeripherals-0.7.26r.jar                   |Advanced Peripherals          |advancedperipherals           |0.7.26r             |DONE      |Manifest: NOSIGNATURE
		cccbridge-1.3.1-forge.jar                         |CC:C Bridge                   |cccbridge                     |1.3.1               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.2+1.18.jar         |Player Animator               |playeranimator                |0.4.2+1.18          |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+17.jar                  |Clumps                        |clumps                        |8.0.0+17            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.9.3-forge.jar                 |Journeymap                    |journeymap                    |5.9.3               |DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.2.0.jar      |CookingForBlockheads          |cookingforblockheads          |12.2.0              |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+22.jar               |Controlling                   |controlling                   |9.0+22              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.6.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.6      |DONE      |Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-8.0.42.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |8.0.42              |DONE      |Manifest: NOSIGNATURE
		framedcompactdrawers-1.18-4.1.0.jar               |Framed Compacting Drawers     |framedcompactdrawers          |1.18-4.1.0          |DONE      |Manifest: NOSIGNATURE
		condensedmilk-1.18.2_1.0r.jar                     |Condensedmilk                 |condensedmilk                 |1.18.2_1.0r         |DONE      |Manifest: NOSIGNATURE
		farmingforblockheads-forge-1.18.2-10.0.2.jar      |Farming for Blockheads        |farmingforblockheads          |10.0.2              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.52.jar                |Bookshelf                     |bookshelf                     |13.2.52             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		create-confectionery1.18.2_v1.0.8.jar             |Create Confectionery          |create_confectionery          |1.0.8               |DONE      |Manifest: NOSIGNATURE
		balm-3.2.2+0.jar                                  |Balm                          |balm                          |3.2.2+0             |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.3.jar                              |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.205.jar             |CraftTweaker                  |crafttweaker                  |9.1.205             |DONE      |Manifest: NOSIGNATURE
		rubidium_extras-1.18.2_v1.3.2.jar                 |Rubidium Extras               |rubidium_extras               |1.18.2_v1.3.2       |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.1-universal.jar                 |Forge                         |forge                         |40.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.18.2-4.1.1494-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1494            |DONE      |Manifest: NOSIGNATURE
		emotecraft-for-MC1.18.2-2.2.7-b.build.47-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.47    |DONE      |Manifest: NOSIGNATURE
		createbb-1.6.jar                                  |Create: Broken Bad            |createbb                      |1.18.2-1.6          |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		smoothchunk-1.18.2-1.9.jar                        |Smoothchunk mod               |smoothchunk                   |1.18.2-1.9          |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar  |EnchantmentDescriptions       |enchdesc                      |10.0.12             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |DONE      |Manifest: NOSIGNATURE
		create_brass_coated-0.2.2-1.18.2.jar              |Create: Brass Coated          |create_brass_coated           |0.2.2-1.18.2        |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.134.jar               |Biomes O' Plenty              |biomesoplenty                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.6.jar                       |Jade                          |jade                          |5.2.6               |DONE      |Manifest: NOSIGNATURE
		ColaMixinConfig-v1.0.2.jar                        |ColaConfig                    |caffeineconfig                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |DONE      |Manifest: NOSIGNATURE
		bendy-lib-forge-2.1.1.jar                         |Bendy lib                     |bendylib                      |2.1.1               |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-8.3.590.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |8.3.590             |DONE      |Manifest: NOSIGNATURE
		TextruesRubidiumOptions-1.0.4-mc1.18.2.jar        |TexTrue's Rubidium Options    |reeses_sodium_options         |1.0.4-mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.8.0.jar                   |Curios API                    |curios                        |1.18.2-5.0.8.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		create-factory-1.18.2-v1.6.jar                    |Create: Factory               |create_factory                |1.6                 |DONE      |Manifest: NOSIGNATURE
		rubidium-extra-0.4.16+mc1.18.2-build.57.jar       |Rubidium Extra                |sodiumextra                   |0.4.16+mc1.18.2-buil|DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-mc1.18-1.5.1.jar              |EntityCulling                 |entityculling                 |1.5.1               |DONE      |Manifest: NOSIGNATURE
		DrawersTooltip-1.18.2-forge-5.0.0.jar             |Drawers Tooltip               |drawerstooltip                |5.0.0               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |DONE      |Manifest: NOSIGNATURE
		miners_delight-1.18.2-1.0.3.jar                   |Miner's Delight               |miners_delight                |1.18.2-1.0.3        |DONE      |Manifest: NOSIGNATURE
		create_central_kitchen-1.18.2-for-create-0.5.0.i-1|Create: Central Kitchen       |create_central_kitchen        |1.2.1               |DONE      |Manifest: NOSIGNATURE
		TwilightDelight-1.18.2-1.2.0-Alpha.jar            |Twilight Delight              |twilightdelight               |1.2.0               |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.89-forge.jar                    |Architectury                  |architectury                  |4.11.89             |DONE      |Manifest: NOSIGNATURE
		createchunkloading-1.2.1-forge.jar                |Create Chunkloading           |createchunkloading            |1.2.1               |DONE      |Manifest: NOSIGNATURE
		rer-2.5.2.jar                                     |Roughly Enough Resources      |roughlyenoughresources        |2.5.2               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.2               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		cc-tweaked-1.18.2-1.101.2.jar                     |CC: Tweaked                   |computercraft                 |1.101.2             |DONE      |Manifest: NOSIGNATURE
		largemeals-1.18.2-2.0.jar                         |Large Meals                   |largemeals                    |1.18.2-2.0          |DONE      |Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4.7.jar    |Oh The Biomes You'll Go       |byg                           |1.4                 |DONE      |Manifest: NOSIGNATURE
		BetterF3-3.0.0-Forge-1.18.2.jar                   |BetterF3                      |betterf3                      |3.0.0               |DONE      |Manifest: NOSIGNATURE
		JadeAddons-1.18.2-forge-2.4.1.jar                 |Jade Addons                   |jadeaddons                    |2.4.1               |DONE      |Manifest: NOSIGNATURE
		Delightful-1.18.2-3.2.1.jar                       |Delightful                    |delightful                    |3.2.1               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		createaddition-1.18.2-20230203a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20230203a    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 33a27843-a30e-4e72-b7b8-cfe4af277bb9
	FML: 40.2
	Forge: net.minecraftforge:40.2.1
	Flywheel Backend: GL33 Instanced Arrays
```

### Logs

```
[18:10:06] [Server thread/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Couldn't place player in world
com.google.gson.JsonSyntaxException: Unknown type: vectorwing.farmersdelight.common.loot.function.CopySkilletFunction@643a4332
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:120) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2331!/:?] {}
	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$Serializer.m_7219_(LootPoolSingletonContainer.java:141) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:43) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.entries.LootItem$Serializer.m_7219_(LootItem.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:80) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.entries.LootPoolEntryContainer$Serializer.m_6170_(LootPoolEntryContainer.java:74) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.serialize(GsonAdapterFactory.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.ArrayTypeAdapter.write(ArrayTypeAdapter.java:95) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2331!/:?] {}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:204) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.LootPool$Serializer.serialize(LootPool.java:187) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155) ~[gson-2.8.9.jar%2331!/:?] {}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:278) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.level.storage.loot.LootTable$Serializer.serialize(LootTable.java:252) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81) ~[gson-2.8.9.jar%2331!/:?] {}
	at com.google.gson.Gson.toJson(Gson.java:735) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:628) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at com.google.gson.Gson.toJsonTree(Gson.java:607) ~[gson-2.8.9.jar%2331!/:?] {re:mixin}
	at uk.me.desert_island.rer.RoughlyEnoughResources.sendLootToPlayers(RoughlyEnoughResources.java:53) ~[rer-2.5.2.jar%23112!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,re:mixin}
	at net.minecraft.server.players.PlayerList.handler$zdk000$onPlayerConnect(PlayerList.java:910) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:239) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:classloading,pl:rei_plugin_compatibilities:B,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23125!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}
```

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by MCBEModder2020** [comment] 2023-02-21 23:33
issue not present with only farmers delight

**Comment by MCBEModder2020** [comment] 2023-02-21 23:42
rei seems to be the issue

**Comment by MCBEModder2020** [comment] 2023-02-22 00:04
dupe of #565

**Comment by vectorwing** [comment] 2023-04-30 02:40
Yeah, it's a dupe of the issue you mentioned. For now, disabling RER should work, but I'm looking into whether the fix must be on my end.

**Closed as completed by vectorwing** 2023-04-30 02:40 UTC
