### ISSUE TITLE
Knife duplicates on repair

### ISSUE THREAD

**Issue by Rowyfo** [vectorwing/FarmersDelight#51] opened 2020-08-09 23:05 UTC
Repairing the knife duplicates the item.

**Comment by vectorwing** [comment] 2020-08-12 15:02
Just a reminder: please follow the issue template in the future, with steps to reproduce, mod versions etc.

That said, yeah, this seems to be happening. I recall reporting the exact same issue to Immersive Engineering, and they fixed it rather fast: https://github.com/BluSunrize/ImmersiveEngineering/commit/07623b5553fc72677a0c88fa57029cd954d8127e

I might take a look at what they did and see if it works on FD's case.

**Comment by vectorwing** [comment] 2020-08-13 14:36
Fixed on commit: https://github.com/vectorwing/FarmersDelight/commit/6d4c54f3b20fe5eac347386b889da16d2feb205d

**Closed as completed by vectorwing** 2020-08-13 14:36 UTC
Labels: bug
