### ISSUE TITLE
Kicked out from vanila server with Internal exeption

### ISSUE THREAD

**Issue by i218** [vectorwing/FarmersDelight#805] opened 2023-08-30 19:22 UTC
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.3

### Forge version

40.2.9

### Description

Kicked out from vanila server with this msg 
![image](https://github.com/vectorwing/FarmersDelight/assets/62020768/6e20b72a-445c-4936-aa47-7931f635e46f)
(with only Farmer's Delight installed same thing happens)
Singleplayer works normaly.

### Steps to reproduce

Trying to connect vanila server.
Server works like that, but i cant enter vanila.
Velocity (with plugin) -> Vanila -> Modded

### Mod list

It may be easier to read like that:
[modlist.txt](https://github.com/vectorwing/FarmersDelight/files/12479422/modlist.txt)

(list of mods not needed btw, cause bug works with Farmer's Delight only installed)
But full list is here:
notenoughcrashes-4.1.4+1.18.2-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.1.4+1.18.2        |DONE      |Manifest: NOSIGNATURE
		2.auudio_forge_1.0.3_MC_1.18-1.18.2.jar           |Auudio                        |auudio                        |1.0.3               |DONE      |Manifest: NOSIGNATURE
		1. ForgeClientResetPacket-0.1.0.jar               |Client Reset Packet           |clientresetpacket             |0.0.5               |DONE      |Manifest: NOSIGNATURE
		ExtendedCrafting-1.18.2-4.1.2.jar                 |Extended Crafting             |extendedcrafting              |4.1.2               |DONE      |Manifest: NOSIGNATURE
		laserio-1.4.3.jar                                 |LaserIO                       |laserio                       |1.4.3               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.30.6_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.30.6              |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+23.jar               |Controlling                   |controlling                   |9.0+23              |DONE      |Manifest: NOSIGNATURE
		toolleveling-forge-1.18.2-1.4.5.jar               |Tool Leveling                 |toolleveling                  |1.18.2-1.4.5        |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.18.2-10.2.5.465.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.5              |DONE      |Manifest: NOSIGNATURE
		Create_Steam_Rails-1.4.4+forge-mc1.18.2-build.12.j|Create: Steam 'n Rails        |railways                      |1.4.4+forge-mc1.18.2|DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.18.2-4.1.1494-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1494            |DONE      |Manifest: NOSIGNATURE
		2.konkrete_forge_1.6.0_MC_1.18-1.18.2.jar         |Konkrete                      |konkrete                      |1.6.0               |DONE      |Manifest: NOSIGNATURE
		lmft-1.0.1+1.18.2-forge.jar                       |Load My Fucking Tags          |lmft                          |1.0.1+1.18.2        |DONE      |Manifest: NOSIGNATURE
		BetterPingDisplay-1.18.2-1.1.jar                  |Better Ping Display           |betterpingdisplay             |1.1                 |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.18.2-3.3.1.6-10.jar        |Industrial Foregoing          |industrialforegoing           |3.3.1.6             |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar          |Ambient Sounds                |ambientsounds                 |5.0.16              |DONE      |Manifest: NOSIGNATURE
		Botania-1.18.2-435.jar                            |Botania                       |botania                       |1.18.2-435          |DONE      |Manifest: NOSIGNATURE
		wthit-forge-4.13.6.jar                            |wthit                         |wthit                         |4.13.6              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.1      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.10.162.jar                        |OreExcavation                 |oreexcavation                 |1.10.162            |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-5.11.3.jar                           |FramedBlocks                  |framedblocks                  |5.11.3              |DONE      |Manifest: NOSIGNATURE
		MysticalCustomization-1.18.2-3.1.2.jar            |Mystical Customization        |mysticalcustomization         |3.1.2               |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.18.2-2.6.37.jar                   |Gobber 2                      |gobber2                       |2.6.37              |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.10.jar                          |WorldEdit                     |worldedit                     |7.2.10+1742f98      |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.18.2-10.2.5.465.jar               |Mekanism: Tools               |mekanismtools                 |10.2.5              |DONE      |Manifest: NOSIGNATURE
		constructionwand-1.18.2-2.9.jar                   |Construction Wand             |constructionwand              |1.18.2-2.9          |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		cc-tweaked-1.18.2-1.101.2.jar                     |CC: Tweaked                   |computercraft                 |1.101.2             |DONE      |Manifest: NOSIGNATURE
		Better+Muffling-1.18.2-1.0.6.jar                  |Better Muffling               |bettermuffling                |1.0.6               |DONE      |Manifest: NOSIGNATURE
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_v1.4.23_mc1.18.2.jar                   |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |Manifest: NOSIGNATURE
		tinkerleveling-0.4.0.jar                          |Tinker Leveling               |tinkerleveling                |0.4.0               |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.18.2-0.4.3.jar                  |Framework                     |framework                     |0.4.3               |DONE      |Manifest: NOSIGNATURE
		Thermal-CodeChickenLib-1.18.2-4.1.4.488-universal.|CodeChicken Lib               |codechickenlib                |4.1.4.488           |DONE      |Manifest: 31:e6:db:63:47:4a:6e:e0:0a:2c:11:d1:76:db:4e:82:ff:56:2d:29:93:d2:e5:02:bd:d3:bd:9d:27:47:a5:71
		Cyclic-1.18.2-1.7.14.jar                          |Cyclic                        |cyclic                        |1.18.2-1.7.14       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		fashion-1.18.2-4.0.0.1.jar                        |Fashion Mod                   |fashion                       |1.18.2-4.0.0.1      |DONE      |Manifest: NOSIGNATURE
		ftb-rhino-forge-1802.2.1-build.255.jar            |Rhino                         |rhino                         |1802.2.1-build.255  |DONE      |Manifest: NOSIGNATURE
		createbigcannons-forge-1.18.2-0.5.2.jar           |Create Big Cannons            |createbigcannons              |0.5.2-nightly-cc34fb|DONE      |Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.3.jar                         |Cucumber Library              |cucumber                      |5.1.3               |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.11-build.177.jar         |FTB Library                   |ftblibrary                    |1802.3.11-build.177 |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.11-build.107.jar           |FTB Teams                     |ftbteams                      |1802.2.11-build.107 |DONE      |Manifest: NOSIGNATURE
		Tinkers+Reforged+1.18.2-2.0.8.jar                 |Tinkers Reforged              |tinkers_reforged              |2.0.8               |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.4.8+1.18.2-universal.jar  |Minecraft Comes Alive         |mca                           |7.4.8+1.18.2        |DONE      |Manifest: NOSIGNATURE
		ftb-item-filters-forge-1802.2.8-build.50.jar      |Item Filters                  |itemfilters                   |1802.2.8-build.50   |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.2.266.jar                          |Just Enough Items             |jei                           |9.7.2.266           |DONE      |Manifest: NOSIGNATURE
		ftb-kubejs-forge-1802.5.5-build.569.jar           |KubeJS                        |kubejs                        |1802.5.5-build.569  |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-11.7.0.jar              |Applied Energistics 2         |ae2                           |11.7.0              |DONE      |Manifest: NOSIGNATURE
		bdlib-1.19.3.7-mc1.18.2.jar                       |BdLib                         |bdlib                         |1.19.3.7            |DONE      |Manifest: NOSIGNATURE
		MekanismMatter-1.18.2-2.0.4.jar                   |Mekanism Matter               |mekanismmatter                |2.0.0               |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.18.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		badpackets-forge-0.1.2.jar                        |Bad Packets API               |badpackets                    |0.1.2               |DONE      |Manifest: NOSIGNATURE
		badmobs-1.18.2-13.01.jar                          |BadMobs                       |badmobs                       |13.01               |DONE      |Manifest: NOSIGNATURE
		pneumaticcraft-repressurized-1.18.2-3.6.0-19.jar  |PneumaticCraft: Repressurized |pneumaticcraft                |1.18.2-3.6.0-19     |DONE      |Manifest: NOSIGNATURE
		ftb-backups2-forge-1.18.2-1.0.19.jar              |FTB Backups 2                 |ftbbackups2                   |1.0.19              |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.18.1-2.2.3.jar                     |Guide-API VP                  |guideapi_vp                   |2.2.3               |DONE      |Manifest: NOSIGNATURE
		WaveyCapes-1.2.0-Forge-1.18.2.jar                 |WaveyCapes Mod                |waveycapes                    |1.2.0               |DONE      |Manifest: NOSIGNATURE
		Мелкий-Список Модов-catalogue-1.6.2-1.18.2.jar    |Catalogue                     |catalogue                     |1.6.2               |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.9.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.9             |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.209.jar             |CraftTweaker                  |crafttweaker                  |9.1.209             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.18.2-10.2.5.465.jar                    |Mekanism                      |mekanism                      |10.2.5              |DONE      |Manifest: NOSIGNATURE
		AEAdditions-1.18.2-3.2.7.jar                      |AE Additions                  |ae2additions                  |3.2.7               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.9-universal.jar                 |Forge                         |forge                         |40.2.9              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		BloodMagic-1.18.2-3.2.6-41.jar                    |Blood Magic                   |bloodmagic                    |1.18.2-3.2.6-41     |DONE      |Manifest: NOSIGNATURE
		BrandonsCore-1.18.2-3.1.9.280-universal.jar       |Brandon's Core                |brandonscore                  |3.1.9.280           |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		Draconic-Evolution-1.18.2-3.0.29.524-universal.jar|Draconic Evolution            |draconicevolution             |3.0.29.524          |DONE      |Manifest: 53:bb:a0:11:bd:61:e2:1a:e2:cb:fd:f8:4f:e4:cd:a5:cc:12:f4:43:f0:78:68:3b:e1:62:c6:78:3b:27:ff:fe
		MysticalAgriculture-1.18.2-5.1.4.jar              |Mystical Agriculture          |mysticalagriculture           |5.1.4               |DONE      |Manifest: NOSIGNATURE
		MysticalAgradditions-1.18.2-5.1.3.jar             |Mystical Agradditions         |mysticalagradditions          |5.1.3               |DONE      |Manifest: NOSIGNATURE
		ZeroCore2-1.18.2-2.1.34.jar                       |Zero CORE 2                   |zerocore                      |1.18.2-2.1.34       |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		thermal-cofh_core-1.18.2-9.2.1.39.jar             |CoFH Core                     |cofh_core                     |9.2.1               |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.18.2-9.2.0.46.jar            |Thermal Series                |thermal                       |9.2.0.46            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_integration-1.18.2-9.2.0.16.jar           |Thermal Integration           |thermal_integration           |9.2.0.16            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_innovation-1.18.2-9.2.0.17.jar            |Thermal Innovation            |thermal_innovation            |9.2.0.17            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.18.2-9.2.0.20.jar             |Thermal Expansion             |thermal_expansion             |9.2.0.20            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		ExNihiloThermal-1.18.2-20220608-014416.jar        |Ex Nihilo: Sequentia - Thermal|exnihilothermal               |1.18.2-20220608-0144|DONE      |Manifest: NOSIGNATURE
		TConstruct-1.18.2-3.6.4.113.jar                   |Tinkers' Construct            |tconstruct                    |3.6.4.113           |DONE      |Manifest: NOSIGNATURE
		panthalassa-1.2.1-1.18.2.jar                      |Panthalassa                   |panthalassa                   |1.2.1               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		titanium-1.18.2-3.5.8-40.jar                      |Titanium                      |titanium                      |3.5.8               |DONE      |Manifest: NOSIGNATURE
		ftb-quests-forge-1802.3.14-build.191.jar          |FTB Quests                    |ftbquests                     |1802.3.14-build.191 |DONE      |Manifest: NOSIGNATURE
		Avaritia-1.1x-1.18.2-4.0.1.6-universal.jar        |Avaritia                      |avaritia                      |4.0.1.1             |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.2-8.4.0-161.jar         |Immersive Engineering         |immersiveengineering          |1.18.2-8.4.0-161    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		firstperson-forge-2.2.2-mc1.18.2.jar              |FirstPersonModel Mod          |firstpersonmod                |2.2.2-mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.6.16_mc1.18.2.jar           |CreativeCore                  |creativecore                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		ExNihiloMekanism-1.18.2-20220608-005057.jar       |Ex Nihilo: Sequentia - Mekanis|exnihilomekanism              |1.18.2-20220608-0050|DONE      |Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.0-mc1.18.2.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.0               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.9-101.jar               |Flywheel                      |flywheel                      |0.6.9-101           |DONE      |Manifest: NOSIGNATURE
		create-alloyed-1.18.2-v1.5a.jar                   |Create: Alloyed               |alloyed                       |1.18.2              |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.1.c.jar                         |Create                        |create                        |0.5.1.c             |DONE      |Manifest: NOSIGNATURE
		createdeco-1.3.3-1.18.2.jar                       |Create Deco                   |createdeco                    |1.3.3-1.18.2        |DONE      |Manifest: NOSIGNATURE
		yawp-1.18.2-0.0.2.9-beta1-forge.jar               |Yet Another World Protector   |yawp                          |0.0.2.9-beta1       |DONE      |Manifest: NOSIGNATURE
		Tinkers-Mantle-1.18.2-1.9.45.jar                  |Mantle                        |mantle                        |1.9.45              |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.5.0_Forge_1.18.2.jar            |Xaero's Minimap               |xaerominimap                  |23.5.0              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.2.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		thermal_cultivation-1.18.2-9.2.0.16.jar           |Thermal Cultivation           |thermal_cultivation           |9.2.0.16            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		Мелкий+ - Конфликтующие рецепты-polymorph-forge-1.|Polymorph                     |polymorph                     |1.18.2-0.45         |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |DONE      |Manifest: NOSIGNATURE
		Tinker_materialis-1.18.2-2.8.6 (1).jar            |Materialis                    |materialis                    |1.18.2-2.8.6        |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |DONE      |Manifest: NOSIGNATURE
		clear-skies-forge-mc1182-2.0.92.jar               |Clear Skies                   |clear_skies                   |2.0.92              |DONE      |Manifest: NOSIGNATURE
		2.fancymenu_forge_2.13.3-2_MC_1.18.2.jar          |FancyMenu                     |fancymenu                     |2.13.3              |DONE      |Manifest: NOSIGNATURE
		2.drippyloadingscreen_forge_2.1.1_MC_1.18.2.jar   |Drippy Loading Screen         |drippyloadingscreen           |2.1.1               |DONE      |Manifest: NOSIGNATURE
		infinitylib-2.1.4.jar                             |InfinityLib                   |infinitylib                   |1.18.2-2.1.4        |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.2               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		ExNihiloSequentia-1.18.2-20221113-044349.jar      |Ex Nihilo: Sequentia          |exnihilosequentia             |1.18.2-20221113-0443|DONE      |Manifest: NOSIGNATURE
		ExNihiloAE-1.18.2-20220607-014628.jar             |Ex Nihilo: Sequentia - AE2 Add|exnihiloae                    |1.18.2-20220607-0146|DONE      |Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.2-1.2.114-universal.jar    |Chisels & bits                |chiselsandbits                |1.2.114             |DONE      |Manifest: NOSIGNATURE
		createaddition-1.18.2-1.0.0.jar                   |Create Crafts & Additions     |createaddition                |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		IBE-Editor-v2.1.1-for-Forge-1.18.2.jar            |IBE Editor                    |ibeeditor                     |2.1.1               |DONE      |Manifest: NOSIGNATURE

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by i218** [comment] 2023-08-30 20:02
There was also another tester with a different message
![image](https://github.com/vectorwing/FarmersDelight/assets/62020768/8de35a0e-9c24-48b2-95b7-4c87a7c43b64)

**Comment by GGrandma** [comment] 2023-09-07 21:00
can reproduce

Minecraft: 1.20.1
Forge: 47.1.0
Farmer's Delight: 1.2.2, 1.2.2a, 1.2.3

**Comment by i218** [comment] 2023-09-09 16:37
Repo?

> can repo
> 
> Minecraft: 1.20.1 Forge: 47.1.0 Farmer's Delight: 1.2.2, 1.2.2a, 1.2.3

**Comment by GGrandma** [comment] 2023-09-10 03:04
Sorry meant reproduce, edited.

**Comment by Hellicious** [comment] 2023-09-19 09:39
Have the same issue, Minecraft version 1.20.1, Forge 47.1.0, Farmer's Delight 1.2.3
![image_2023-09-19_123625089](https://github.com/vectorwing/FarmersDelight/assets/74752712/c7c17632-510c-4b53-a59c-b9e652590554)

**Comment by Xing-C** [comment] 2023-09-24 01:40
This prevented me from joining the bungee server, and I received the same error. After a day of investigation, I found out that it was due to this mod

**Comment by bananababoo** [comment] 2023-09-25 19:25
Had the same issue today, exact same error message as @Hellicious.

**Comment by p0t4t0sandwich** [comment] 2023-09-25 20:20
Just going to throw my two sense in here.
Once Forge 1.20.2 and server proxies get the new protocol all hashed out, this issue is going to become a lot more widespread, as nobody in their right mind would waste resources on a modded hub, especially if they're running multiple modpacks under the same proxy.
It would be in your best interest to finally get this issue properly fixed.

**Comment by vectorwing** [comment] 2023-09-25 21:07
Seems to be similar, or duplicate, to issue #810.

Forge mods are not meant to be compatible with vanilla servers, thus shouldn't be expected to work in such cases. That said, I had no idea so many users were adopting this proxy server system, instead of making a separate modded instance.

Connection errors trigger Netty exceptions, which are apparently swallowed by Forge; so logs provide no information. I have zero clue as to why FD could be causing this, when no other mod does so.

To folks in this thread, please help me out by doing the following steps:
1. Download and install this mod: https://www.curseforge.com/minecraft/mc-mods/spit-it-out
2. Attempt to connect again;
3. Grab both client and server logs, if possible, and post them here.

**Comment by wolflord212312** [comment] 2023-09-25 21:32
Clinet:
https://mclo.gs/spfCkge Latest
https://mclo.gs/UOyBLDb Debug

Proxy:(all the way to the bottom ignore other errors look for DjJewl)
https://mclo.gs/kqOsRn3

Vanilla Server: Ignore other errors
https://mclo.gs/Izro3zl

**Comment by p0t4t0sandwich** [comment] 2023-09-25 21:58
Only mods in use are FD and Spit It Out
## Paper Server With No Proxy
Client (Forge 47.2.0): https://mclo.gs/RkpB99T
Server (Paper 1.20.1 v196): https://mclo.gs/Lchb5re

## Paper Server With Velocity and the Ambassador Velocity plugin
Client (Forge 47.2.0): https://mclo.gs/wILKm6u
Server (Paper 1.20.1 v196): https://mclo.gs/8kx4RnB
Proxy (Velocity v265): https://mclo.gs/FWJyHj5

## Paper Server With Velocity without Ambassador
Client (Forge 47.2.0): https://mclo.gs/MpyczWK
Server (Paper 1.20.1 v196): https://mclo.gs/7wYXgeN
Proxy (Velocity v265): https://mclo.gs/WIPQf8P

**Comment by GGrandma** [comment] 2023-09-25 23:45
## Client
Minecraft: 1.20.1
Forge: 47.1.0
Farmer's Delight: 1.2.3
Spit It Out: 1.0.0
https://mclo.gs/bLkblOo
https://mclo.gs/ppxvpMp

## Server
Velocity: 3.2.0-SNAPSHOT # 265
Paper: 1.20.1 # 170
Plugins: Ambassador, Floodgate, Geyser

**Comment by vectorwing** [comment] 2023-09-26 02:50
After a lot of asking around, I figured out what the problem is, and I have bad news. :(

FD adds a **vanilla recipe book to the Cooking Pot**, and to do so, it must extend the `RecipeBookType` enum. However, vanilla assumes the RecipeBookType enum is non-extendable, while Forge makes it extendable. This works fine in a modded client/server connection, but a vanilla server does not expect the enum to be bigger on the client, which causes the packet to be too large.

Due to the nature of Java enums, there is no good way for me to fix this on FD without completely removing the Recipe Book integration, which is not something I can do. This issue would have to be fixed in either Bungeecord (ignoring modded enum entries) or in NeoForge; nothing I can do on my end.

I'll open an issue in NeoForge regarding this conflict, as it affects consumers of its recipe book integrations.

Sorry for the inconvenience, folks. 😞

**Closed as completed by vectorwing** 2023-09-26 02:50 UTC
Labels: unrelated

**Comment by p0t4t0sandwich** [comment] 2023-09-26 08:32
Thanks for taking the time to look into it! Hopefully they'll be able to figure something out upstream, or worst case, some proxy dev figures out a fix/workaround.

**Comment by p0t4t0sandwich** [comment] 2023-10-03 10:22
So funny story, I had the idea to use Protocolib on the Paper server to just tactical nuke any recipe book packets, and that surprisingly worked. The caveat there being that the recipe book doesn't function, but if you were to have this on a hub server, the recipe book should fix itself when joining the Forge server.
(I also highly doubt you'd make much use of the recipe book on the hub server anyway)

**Comment by i218** [comment] 2023-10-03 18:27
> So funny story, I had the idea to use Protocolib on the Paper server to just tactical nuke any recipe book packets, and that surprisingly worked. The caveat there being that the recipe book doesn't function, but if you were to have this on a hub server, the recipe book should fix itself when joining the Forge server. (I also highly doubt you'd make much use of the recipe book on the hub server anyway)

Could u help me do the same thing pls? (Cause i never heard about Protocolib before)

**Comment by p0t4t0sandwich** [comment] 2023-10-03 20:22
Yeah for sure, I'm drafting up a Git repo today so that others will be able to use it.
I honestly wonder how many of those weird packet errors can be solved this way

**Comment by p0t4t0sandwich** [comment] 2023-10-03 23:21
Got it published here, currently working on a less brutal implementation
https://github.com/p0t4t0sandwich/ModPacketFix/releases

**Comment by Xing-C** [comment] 2023-10-04 07:05
> Got it published here, currently working on a less brutal implementation
Perhaps this is not the correct fix, but it is a good idea

**Comment by p0t4t0sandwich** [comment] 2023-10-04 12:11
Fixed it so that it's a bit smarter with removing the Recipe book packet, it shouldn't effect vanilla users now.
With the way Ambassador reconnects the Forge client, the recipe book is restored when the Forge client logs into the Forge server.
