### ISSUE TITLE
Skillet cannot be enchanted

### ISSUE THREAD

**Issue by Inonedn** [vectorwing/FarmersDelight#938] opened 2024-07-26 15:18 UTC
### Minecraft version

1.21

### Farmer's Delight version

Latest

### Forge version

NeoForge 133

### Description

Skillets can no longer be enchanted, when it should be able to receive the same enchantments as a sword

### Steps to reproduce

N/A

### Mod list

N/A

### Logs

N/A

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment] 2024-07-26 15:37
I'm unable to replicate this on a minimal instance. The Skillet can be used in an Enchanting Table:
![image](https://github.com/user-attachments/assets/a78f9a5b-0677-4c62-9233-bce98c769a86)

**Comment by vectorwing** [comment] 2024-07-26 15:39
That said, I am using an internal override to allow the Skillet to obtain sword enchantments. I haven't actually tagged it as `enchantable` the same way I did to knives, so I can take a look at that later.

**Comment by vectorwing** [comment] 2024-07-26 15:41
It seems the issue is related to the Anvil, not the Enchanting Table. Please add these details when opening issues, as it confused me for a moment.

Indeed, Skillets cannot receive Enchanted Books. I'll fix it on 1.2.5 soon.

**Comment by vectorwing** [comment] 2024-07-29 23:50
Fixed on commit 779c87f.

**Closed as completed by vectorwing** 2024-07-29 23:50 UTC
Labels: bug
