### ISSUE TITLE
When using Optifine or Oculus (Iris forge port) the game crashes on startup if FD is installed. 

### ISSUE THREAD

**Issue by JulianDicken** [vectorwing/FarmersDelight#811] opened 2023-09-17 19:09 UTC
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.47

### Description

When using Optifine or Oculus (Iris forge port) the game crashes on startup if FD is installed. 

### Steps to reproduce

described above

### Mod list

Cant generate a nice modlist but its in the crashlog.

### Logs

https://mclo.gs/uBLu9xB

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by edgarogh** [comment] 2023-12-06 15:54
Issue caused by Create, see https://github.com/vectorwing/FarmersDelight/issues/815#issuecomment-1843180040

**Comment by vectorwing** [comment] 2024-01-21 16:58
This issue seems to be fixed on Create 0.5.1f, as well as the latest release of OptiFine, HD_U_I6.
I couldn't get Oculus to replicate this crash.

Please update Create and your performance mod, and it should be resolved. 👍

**Closed as completed by vectorwing** 2024-01-21 16:58 UTC
