### ISSUE TITLE
[1.16.5] Cooking Pot Recipes not working on server

### ISSUE THREAD

**Issue by Thaumatarge** [vectorwing/FarmersDelight#148] opened 2021-01-24 12:45 UTC
Have been playing with friends on my small personal server with this mod loaded, and after an update of either Forge or this mod, suddenly Cooking Pot recipes stopped working. 

Forge version is 1.16.5-36.0.1
Farmer's Delight version is 0.3.1

Tested with only JEI and Farmer's Delight loaded, and I have checked the logs, but there is nothing in the logs about a failure to load recipes.

**Comment by vectorwing** [comment] 2021-01-30 20:55
Sorry for the delay.

First off: when errors like this happen, always provide a log from your instance, even if it didn't crash. Logs contain vital information for troubleshooting what went wrong; the Bug Report template instructs you to do so.

Regardless, I've gotten more than a few people to report this now, and I replicated it locally. Turns out it's a problem with our **Decomposition** JEI recipe: it's trying to call a tag in the constructor of a recipe category, which happens **before tags are bound**. This ends up crashing the plugin and preventing our JEI integration from loading on server settings.

I'm not sure how to fix this yet, but the call has to be moved somewhere else. Should be fixed in the next dot version. 👍

**Comment by vectorwing** [comment] 2021-02-01 02:59
I wrote a temporary partial fix to this issue that removes the tag check from the improper calls. The JEI screen will show the activators, but the items won't be catalysts to check the recipe when U is pressed.

There seems to be a [PR to fix a related issue](https://github.com/mezz/JustEnoughItems/pull/2227) in JEI in regards to tag syncing, so chances are we're not actually calling the tag wrongly. But I might release this temporary fix anyway, since it fixes the whole plugin crashing.

**Comment by vectorwing** [comment] 2021-02-13 01:36
The aforementioned PR to JEI is now live, and the issue is resolved from their end; the previous tag call should now work. I have marked this as a todo in my project board, so I'll be closing the issue.

**Closed as completed by vectorwing** 2021-02-13 01:36 UTC
Labels: bug, help wanted
