### ISSUE TITLE
[1.19.2]: Basket BlockEntity crashes server on right

### ISSUE THREAD

**Issue by ModernGamingWorld** [vectorwing/FarmersDelight#714] opened 2023-05-12 16:32 UTC
### Description

ok so right clicked a "Farmer's Delight" Basket and seems to have closed/crashed the server, This was brought to me by a player playing my custom pack on a server, so idk how else to explain what's happening here

### Steps to reproduce

Example
1. Right click 
2. server crashes

### Mod list

https://gist.github.com/ModernGamingWorld/9b1502538f4ed28ca64834ae190ea7e8

### Logs

[crash-2023-05-12_04.22.06-server.txt](https://github.com/vectorwing/FarmersDelight/files/11466149/crash-2023-05-12_04.22.06-server.txt)
[latest.log](https://github.com/vectorwing/FarmersDelight/files/11466152/latest.log)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by TelepathicGrunt** [comment] 2023-05-13 01:21
![IMG_0112](https://github.com/vectorwing/FarmersDelight/assets/40846040/336ad461-e94d-4642-b6f6-85fe357a3da6)
![IMG_0113](https://github.com/vectorwing/FarmersDelight/assets/40846040/ba795d2d-76c1-47e6-ba81-30920501c8e5)

Seems like a Dungeons Gear issue. I pinged pat about it in their discord. If no reply for a bit, you can try opening issue report to their repo

**Comment by vectorwing** [comment] 2023-05-13 01:27
Thanks for helping me out with this, @TelepathicGrunt. Since the relevant code in BasketTileEntity was based on the hopper, it might be reproducible on it as well. But I'll follow the issue, in case any changes are required from my end.

**Comment by ModernGamingWorld** [comment] 2023-05-13 01:37
Thanks @TelepathicGrunt, As I have a few modpacks with this mod and Dungeons Gear in it, so Hopefully this will be fixed soon

**Comment by ModernGamingWorld** [comment] 2023-06-02 17:45
Has anyone know if Infamous is working on a fix for this issue, It's been over three weeks and I was hoping it would be fixed before everyone jumps to 1.20 next week

**Comment by vectorwing** [comment] 2023-06-26 23:44
Given this seems related to how a mixin is resolved, rather than an implementation on my end, I'll be closing the issue for now.
Follow this issue for future updates on the bug: https://github.com/Infamous-Misadventures/Dungeons-Gear/issues/242

**Closed as completed by vectorwing** 2023-06-26 23:44 UTC
Labels: integration
