### ISSUE TITLE
[1.18.1] Rice crash

### ISSUE THREAD

**Issue by Numbers949** [vectorwing/FarmersDelight#383] opened 2022-01-16 08:19 UTC
playing around with farming mods and found that rice crashes the game when planted

its 100% rice no other seed or plant dose it, 

got no logs as the game just freezes up,  

don't have a screen grabber at the time 

mod list: [ive tested with without these but could be some config]
.compact o plenty
.blueprint
.better animals plus
.architectury
.scaling heath
.silent lib
.just enough resources
.tetra
.mutil
.decorative+blocks
.infernal mobs
.repurposed structures
.kiwi
.valhelsia structures and core
.dungeon crawl
.This mod
.create
.optifine
.crafttweaker
.boiomes o pelenty
.terrablender
.clumps
.customplayermodels
.appleskin
.tough as nails
.sereneseasons
.autoreglib
.quark
.creadadditon
.just enough items
.flywheel
.attributefix
.forge
 
Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment] 2022-01-16 15:23
Duplicate of issue #379. Please search for similar issues before opening new ones.

**Closed as completed by vectorwing** 2022-01-16 15:23 UTC
