### ISSUE TITLE
Loot table crashes

### ISSUE THREAD

**Issue by GNRL-Washingtoad** [vectorwing/FarmersDelight#772] opened 2023-07-14 04:24 UTC
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2

### Forge version

47.1.0

### Description

Chests in dungeons as well as chests in minecarts crash the game when their loot table is accessed, whether by right clicking or breaking them. I don't know if loot tables in other structures could cause this.

### Steps to reproduce

1. Locate dungeon
2. right click chest
3. game or server crashes

### Mod list

client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.2.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.2        |DONE      |Manifest: NOSIGNATURE
		entity_model_features_forge_1.20-0.2.10.jar       |Entity Model Features         |entity_model_features         |0.2.10              |DONE      |Manifest: NOSIGNATURE
		entity_texture_features_forge_1.20-4.4.5.jar      |Entity Texture Features       |entity_texture_features       |4.4.5               |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.20.1-2.4.11.jar                 |Simple Voice Chat             |voicechat                     |1.20.1-2.4.11       |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.20-16.0.1.jar     |EnchantmentDescriptions       |enchdesc                      |16.0.1              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.20.1-3.0.0.164.jar           |TerraBlender                  |terrablender                  |3.0.0.164           |DONE      |Manifest: NOSIGNATURE
		easierarmortrim-1.0.0-1.20.1.jar                  |Easier Armor Trim Duplication |easierarmortrim               |1                   |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.579.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.579          |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20-4.2.jar                       |GeckoLib 4                    |geckolib                      |4.2                 |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.22.jar                    |Just Enough Items             |jei                           |15.2.0.22           |DONE      |Manifest: NOSIGNATURE
		rubidium-0.6.5.jar                                |Rubidium                      |rubidium                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.4-mc1.20.jar        |NotEnoughAnimations Mod       |notenoughanimations           |1.6.4               |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.1.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.1        |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.1.jar                   |Waystones                     |waystones                     |14.0.1              |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20-1.6.4.jar                           |Oculus                        |oculus                        |1.6.4               |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.20-1.0.0.jar                     |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.0               |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.2-1.20.1.jar                          |Citadel                       |citadel                       |2.4.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.2-mc1.20.jar              |EntityCulling                 |entityculling                 |1.6.2               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20-19.0.15.jar                  |Bookshelf                     |bookshelf                     |19.0.15             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		architectury-9.0.8-forge.jar                      |Architectury                  |architectury                  |9.0.8               |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.3+1.20.1-universal.jar  |Minecraft Comes Alive         |mca                           |7.5.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.20.x-(v.4.1.2).jar   |Additional Structures         |additionalstructures          |4.1.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20-7.0.4.jar                         |Balm                          |balm                          |7.0.4               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.0.2-1.20.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		justzoom_forge_1.0.1_MC_1.19.4(1).jar             |Just Zoom                     |justzoom                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.0-universal.jar                 |Forge                         |forge                         |47.1.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		konkrete_forge_1.6.1-2_MC_1.20.jar                |Konkrete                      |konkrete                      |1.6.1               |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v8.0.0-1.20.1-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment] 2023-07-14 04:25
Duplicate of #762. Please update to version 1.2.2a to fix it.

**Closed as completed by vectorwing** 2023-07-14 04:25 UTC
Labels: duplicate
