### ISSUE TITLE
[Forge 39.0.18, 1.18.1] Server Crash when activating rice.

### ISSUE THREAD

**Issue by SympathyforDevil** [vectorwing/FarmersDelight#379] opened 2022-01-13 04:52 UTC
Description
When playing singleplayer , whenever i try to plant or click on a block with rice in my hand, the game freezes and the crash occurs. I then get the message an unexpected crash has happened with Code 0 and no crash report.
In Multiplayer, doing the same produces the following crash log.

Steps to reproduce:
Client : Right click on a block or try to plant rice.

Server : The same

Expected behavior:
Plant the Rice and not crash.

Logs
[crash-2022-01-13_06.33.19-client.txt](https://github.com/vectorwing/FarmersDelight/files/7859973/crash-2022-01-13_06.33.19-client.txt)

Mod list:
    Macaw's Bridges
Farmer's Delight
Quark Oddities
EnchantmentDescriptions  
TerraBlender
Blue Skies  
Biomes O' Plenty
Tree Harvester  
Just Enough Items  
Macaw's Windows
Waystones 
Collective 
Advanced Netherite
Citadel 
Alex's Mobs
AutoRegLib
Traveler's backpack
Storage Drawers
Serene Seasons
Configured
Inventory Hud+(forge edition)
Better Animals Plus
MrCrayfish's Furniture Mod
Architectury
Ai-Improvements
Balm
Forge
Quark
AppleSkin
Valhesia Core
Valhesia Structures
Forbidden & Arcanus
Supplementaries
Structure Gel API
Selene 
Corpse 
Full List

**Comment by vectorwing** [comment] 2022-01-13 05:02
What the... the exception is saying the Forge tag's field in code doesn't exist?!

This is kind of a bizarre error to have. It works fine on my local instances with other mods alongside it, so I suspect two things:
- Some mod is wrongly meddling with the field `DIRT` in code;
- This Forge version has some problem with tags.

I suggest making a minimal instance and retrying. See if FD and this Forge version alone cause the error, or take mods out until it stops happening in a test world. I'll take a further look later.

**Comment by vectorwing** [comment] 2022-01-13 05:12
Turns out Forge deleted their DIRT tag on version 39.0.18 without warning, which broke this version of FD.
I'll have to update and use the vanilla one. Please downgrade your Forge version to 39.0.17 in the meantime.

**Comment by IacobusBarbatus** [comment] 2022-01-13 21:53
> Turns out Forge deleted their DIRT tag on version 39.0.18 without warning, which broke this version of FD.
I'll have to update and use the vanilla one. Please downgrade your Forge version to 39.0.17 in the meantime.

I can confirm the bug on Forge 39.0.19 as well, so it seems the deletion of the DIRT tag is not a one-off accident.

**Comment by JulJuls** [comment] 2022-01-15 15:29
Even in Forge 39.0.20.
Vampirism too had a similar problem with DIRT tag, that made servers crash. Seem to be a common problem in forge versions 39.0.18+. Maybe rolling back to 39.0.17 MAY solve the issue, when it's possible.

**Comment by lamoyrl90** [comment] 2022-01-16 00:07
I've been planting rice in water fine, but this happened when I right-clicked on an immature potato crop with rice in my main hand.

https://pastebin.com/pRzTxqiP

MC 1.18.1
Forge 39.0.19
FD 1.18.1-1.0.1

**Comment by vectorwing** [comment] 2022-01-16 00:23
Just to clarify, for the folks coming in with more reports: the issue is known, and a patch will be released eventually.

As of version **39.0.18**, Forge has removed the `forge:dirt` tag in favor of the vanilla `minecraft:dirt` tag. Since FD depended on the Forge tag for its mechanics, it breaks under versions newer than this one.

Downgrade your Forge version for now, until the next patch comes out. 👍

**Closed as completed by vectorwing** 2022-01-16 00:23 UTC
Labels: bug
