### ISSUE TITLE
[Forge 1.18.1] CTD and upon relogging in chunck error

### ISSUE THREAD

**Issue by AlucardWolf** [vectorwing/FarmersDelight#393] opened 2022-01-21 06:09 UTC
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
I recently downloaded Farmers delight although the skillet is works properly the The add-on for the famers delight that adds a cooking pot caused some sort of issue where the game crashes to launcer and when relogging in it creates a chunk error where it was place. i tested it again and it does the exact same thing.

**Steps to reproduce:**
By simply placing the cooking pot on any surface wheather  it be on top of the stove or any other surfaces

**Expected behavior:**
Just placing it on the surface. will possible crash the game.

**Logs**
Even if the game didn't crash, please submit your client/server logs as well. They contain vital information to troubleshoot the issue.

**Screenshots**

**Mod list:**
Modlist is listed in the crash post with attched file.
Thank you for helping with the project! Your reports are appreciated!
[crash-2022-01-20_21.43.11-server.txt](https://github.com/vectorwing/FarmersDelight/files/7910795/crash-2022-01-20_21.43.11-server.txt)
![2022-01-20_22 06 55](https://user-images.githubusercontent.com/79693616/150475306-6660f7be-5c11-4cca-83c9-7d04b347e047.png)
![2022-01-20_22 07 16](https://user-images.githubusercontent.com/79693616/150475314-21a9d66e-b3d2-407b-8c3c-98887b7ccc31.png)

version 1.18.1 1.0.2 Jar

**Comment by vectorwing** [comment] 2022-01-21 19:37
Duplicate of issue #390.

Forge 39.0.45 removed a method that FD was still using, causing a crash when placing the pot.
Please update to version 1.0.3 on CurseForge. 👍

**Closed as completed by vectorwing** 2022-01-21 19:37 UTC
