### ISSUE TITLE
[1.16.4] Crash on startup with Java 8 AdoptOpenJDK OpenJ9

### ISSUE THREAD

**Issue by QuerrixTU** [vectorwing/FarmersDelight#236] opened 2021-03-23 19:12 UTC
Description :
When I set the JVM to the Opjen9J version of java 8 the game crash when it start loading Farmer's Delight. (I use Java 8 AdoptOpenJDK OpenJ9 for performance purpose it reduce the loading time and decrease ram usage.)

Steps to reproduce :
Install Java 8 Open9J and set the javaw.exe as source for JVM in The Minecraft Launcher.

Expected behavior :
A crash when forge start loading Farmer's Delight.

Logs :
Crash report : https://pastebin.com/AiFVasBt
Logs : https://pastebin.com/srceykSZ
Debug : https://pastebin.com/ERED1VFy

Screenshots :
![2021-03-23_20 06 22](https://user-images.githubusercontent.com/44301023/112203854-441dc100-8c13-11eb-8396-f0689e0d4b55.png)

Mod list :
forge-1.16.5-36.1.2-client.jar
farmersDelight-1.16.3-0.3.2.jar
forge-1.16.5-36.1.2-universal.jar

**Comment by vectorwing** [comment] 2021-03-23 19:16
Duplicate of issue #190 again... Please search for closed issues before opening new ones.

**Closed as completed by vectorwing** 2021-03-23 19:16 UTC
Labels: duplicate
