### ISSUE TITLE
[1.16.3+] Error loading mod when running with OpenJ9

### ISSUE THREAD

**Issue by markusxu** [vectorwing/FarmersDelight#234] opened 2021-03-23 08:22 UTC
**Description**
Error loading mod when running with OpenJ9.

**Steps to reproduce:**
I downloaded and installed OpenJ9 and specified it as the JAVA directory to start the MC

**Expected behavior:**
MC starts normally, but when running to load the mod file, MC reports an error but not crash. When I remove the FarmersDelight MOD, the MC runs fine.

**Logs**
[crash-2021-02-10_12.50.59-fml.txt](https://github.com/vectorwing/FarmersDelight/files/6187948/crash-2021-02-10_12.50.59-fml.txt)

**Mod list:**
Forge Version : 35.1.37
See the LOG

Note: I saw that someone had posted a related issue before, but he closed it on his own and I didn't quite understand his description

**Comment by vectorwing** [comment] 2021-03-23 14:11
As you mentioned, this is a duplicate of issue #190, where this exact problem has been extensively discussed. It involves an issue with OpenJ9 and code compatibility. It has been fixed as of a recent nightly version of OpenJ9 linked here:

https://github.com/vectorwing/FarmersDelight/issues/190#issuecomment-796591847

As for FD, the next version will change something that should hopefully not trigger this crash again. If the fix above doesn't work, consider changing back to a Hotspot version of Java until then.

**Closed as completed by vectorwing** 2021-03-23 14:11 UTC
Labels: duplicate
