### ISSUE TITLE
[1.16.4] Saplings don't grow on rich soil.

### ISSUE THREAD

**Issue by othuntgithub** [vectorwing/FarmersDelight#109] opened 2020-12-22 06:54 UTC
**Description**

- Saplings grew on 1.15.2, but they won't on 1.16.4.

**Steps to reproduce:**

- Put a sapling on rich soil.

**Expected behavior:**

- Let it works like 1.15.2.

**Mod list:**

- Farmer's Delight v0.2.4b

**Comment by vectorwing** [comment] 2020-12-22 12:51
Duplicate of issue #96.

**Closed as completed by vectorwing** 2020-12-22 12:51 UTC
