### ISSUE TITLE
Recipes for cooking pot and basin not working

### ISSUE THREAD

**Issue by hunterwiles** [vectorwing/FarmersDelight#898] opened 2024-04-12 03:37 UTC
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.4

### Forge version

43.3.0

### Description

Most of the cooking recipes are not working and having forgotten assets in JEI recipes

### Steps to reproduce

1. Try to cook
2. Doesn't work

### Mod list

https://www.curseforge.com/minecraft/modpacks/notamodpack

The mod list is in there. There are 93+ and I can't copy paste it

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment] 2024-07-30 02:13
Please post your logs here, otherwise I don't have enough information to assist you.
>Most of the cooking recipes are not working and having forgotten assets in JEI recipes

Do you mean that JEI shows red barrier blocks in place of items? If so, chances are an add-on is breaking ingredient tags. Try disabling add-ons and see if the issue is fixed.

**Comment by vectorwing** [comment] 2024-10-01 00:30
Closing this issue for now. Feel free to reopen with the info requested above.

**Closed as completed by vectorwing** 2024-10-01 00:30 UTC
