### ISSUE TITLE
[1.16.3] goo incompatibility

### ISSUE THREAD

**Issue by najlitarvan** [vectorwing/FarmersDelight#95] opened 2020-12-07 07:02 UTC
**Description**
goo doesn't add values to items

**Steps to reproduce:**
install goo and its dependencies and the farmers delight mod

**Expected behavior:**
vanilla items get values and modded items that are not created from vanilla or custom crafting recipes get not gooifable

**Screenshots**
what happened
![image](https://user-images.githubusercontent.com/43792439/101319332-15e1c480-3862-11eb-812a-cffa74695833.png)
what was expected
![image](https://user-images.githubusercontent.com/43792439/101319533-71ac4d80-3862-11eb-81ec-978ca77412bb.png)

**Mod list:**
aequivaleo-0.1.18-ALPHA-universal.jar
FarmersDelight-1.16.3-0.2.4b.jar
Goo-1.16.3-0.8.0.2.jar
Patchouli-1.16.2-47.jar

can't really send crash log since the game itself doesn't crash

**Comment by vectorwing** [comment] 2020-12-07 16:29
Tried this out using your exact mod list (although you forgot to tell me the Forge version), and the logs do have some info on them:
https://paste.ee/p/odrh6#s=0&l=693

Honestly, I'm stumped. These error messages don't tell me much beyond that Aequivaleo's iterators failed to run with my mod present, but nothing about **why** it failed. I might have to ask its dev about it; maybe I'm doing something dumb on register.

I'll update you here if I find anything.

**Comment by najlitarvan** [comment] 2020-12-07 17:43
forge 34.1.42, already told about it on their discord but the more the merrier and a dev is more likely to get bigger attention

**Comment by vectorwing** [comment] 2020-12-07 17:55
Do you have a link to their Discord server? I couldn't find one around their mod pages or GitHub.

**Comment by najlitarvan** [comment] 2020-12-07 17:58
here it is https://discord.gg/dRz7NptW
and its better to look at forge its the last line btw

**Comment by vectorwing** [comment] 2020-12-13 02:42
OK, so I discussed this issue with the devs of Aequivaleo, and apparently it's not an issue with FD per se... but it helped them spot something in their InnerNode implementation caused by recipes that resolve to the same output (a plank). Since the Cutting Board has multiple salvaging recipes, it was crashing their recipe graph.

I'll close the issue for now as I cannot do much about it, but the devs seem to be looking into it. 👍

**Closed as completed by vectorwing** 2020-12-13 02:42 UTC
Labels: bug, help wanted
