### ISSUE TITLE
[FarmersDelight-1.18.1-1.0.1]

### ISSUE THREAD

**Issue by superroksak** [vectorwing/FarmersDelight#394] opened 2022-01-21 11:16 UTC
Morning all,

Been using Farmer's Delight, enjoying it a whole bunch. Worked fine on 19/01/2022, and stopped the next morning. No players have been able to connect to server with mod, log showing the following:
<html><body>

```
[21Jan2022 11:04:24.920] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
--
  | java.lang.NoSuchMethodError:  'net.minecraft.nbt.CompoundTag  vectorwing.farmersdelight.common.block.entity.SyncedBlockEntity.save(net.minecraft.nbt.CompoundTag)'
  | at  vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.writeItems(CookingPotBlockEntity.java:110)  ~[FarmersDelight-1.18.1-1.0.1.jar%2341!/:1.18.1-1.0.1]
  | at  vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.m_5995_(CookingPotBlockEntity.java:441)  ~[FarmersDelight-1.18.1-1.0.1.jar%2341!/:1.18.1-1.0.1]
  | at  net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923) ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045) ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]
  | at  net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76)  ~[server-1.18.1-20211210.034407-srg.jar%2347!/:?]

<!--EndFragment-->
</body>
</html>
```

I've checked that file versions are all correct. Affecting all users who try to connect.

**Comment by superroksak** [comment] 2022-01-21 11:22
Minecraft 1.18.1
Forge 39.0.55, but tested on versions as low as 39.0.10

**Comment by vectorwing** [comment] 2022-01-21 19:37
Duplicate of issue #390.

Forge 39.0.45 removed a method that FD was still using, causing a crash when placing the pot.
Please update to version **1.0.3** on CurseForge. 👍

**Closed as completed by vectorwing** 2022-01-21 19:37 UTC
