### ISSUE TITLE
[1.16.5] Crashing on launch.

### ISSUE THREAD

**Issue by Possibly-Pos** [vectorwing/FarmersDelight#190] opened 2021-02-16 10:38 UTC
Game is crashing on launch. java 8 used.

https://paste.ee/p/wvLGq

![image](https://user-images.githubusercontent.com/40701814/108051673-29a36700-7019-11eb-851e-f8fb016df81b.png)

Forge 36.0.15
FD 0.3.2

**Comment by vectorwing** [comment] 2021-02-16 14:32
Weird. Did you get this just once, or have you tried booting again? Sometimes Forge can be temperamental.
Anyway, I'll need your **latest.log** to debug it.

**Comment by Possibly-Pos** [comment] 2021-02-17 19:33
Every time I launch.

https://paste.ee/p/hVBC5

**Comment by TrialDragon** [comment] 2021-02-18 07:31
Sorry to dirty up the comments, but I'm having the same issue when I launch my server, though not on clientside.
Forge Ver: forge-1.16.5-36.0.42
FarmersDelight Ver: FarmersDelight-1.16.3-0.3.2
PasteBin crash report: https://pastebin.com/q482h1KB
PasteBin latest.log: https://pastebin.com/KnpAtRj0

**Comment by Hubry** [comment] 2021-02-18 15:44
This is extremely likely to be caused by your choice of a JVM to run the game being OpenJ9. Please try with HotSpot?
(Also note that ModLauncher is supposed to stop the game from even attempting to start on OpenJ9, but the check is broken)

**Comment by TrialDragon** [comment] 2021-02-19 03:10
Hey, @Hubry , thanks for the solution. Hotspot works for me and my server is up and running. Can you explain why J9 would cause such an issue btw? Or a link that can clarify this.

**Comment by Hubry** [comment] 2021-02-19 10:51
Well, the cause of the crash is simply that typetools (a library that Forge's event bus is using) uses JVM internals for a few things, and these internals are different on OpenJ9, which makes it fail a lookup it is doing when a mod subscribes to events manually. See the issue above your comment.

This JVM was blacklisted in modlauncher apparently because of some ASM transformation weirdness (see [commit message here](https://github.com/cpw/modlauncher/commit/1f9473a28ad910ef42539f7f789f63afa4cdbf8d)), but there are other problematic spots like around runtime enum changes.

**Comment by ZekerZhayard** [comment] 2021-02-21 04:37
https://github.com/MinecraftForge/typetools/pull/3
I recommend that move `CropPatchGeneration.onBiomeLoad` method to another class.

**Comment by 3TUSK** [comment] 2021-02-21 21:23
It is also worth pointing out that, by relying on static initializer, you are accidentally accessing your `RegistryObjects` too early. The following stacktrace are from the linked issue ticket above:

```
Caused by: java.lang.NullPointerException: Registry Object not present: farmersdelight:wild_cabbages
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_281] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[forge:?] {re:mixin,re:classloading}
	at vectorwing.farmersdelight.world.CropPatchGeneration.<clinit>(CropPatchGeneration.java:22) ~[farmersdelight:1.16.3-0.3.2] {re:classloading}
	... 14 more
```

This was in turn occured during

```
java.lang.ExceptionInInitializerError: null
	at vectorwing.farmersdelight.FarmersDelight.<init>(FarmersDelight.java:35) ~[farmersdelight:1.16.3-0.3.2] {re:classloading}
```

Of course your `ModBlocks` won't be ready when your mod is still constructing, and the registry events have not been dispatched yet.

~~Please consider migrating your `Feature<?>` registration, i.e. these~~

https://github.com/vectorwing/FarmersDelight/blob/8adb746d89e9aeeb4e963cbfe8204e6edf52a5ad/src/main/java/vectorwing/farmersdelight/world/CropPatchGeneration.java#L36-L49  

~~to `DeferredRegister` as well.~~ Edit: for `ConfiguredFeature` you apparently cannot use registry event, see below

**Comment by vectorwing** [comment] 2021-02-26 22:49
I wasn't aware there was a DeferredRegister for Features, that's good to know. Glad to know people are spotting these details! 😄
Gonna put a marker on this to enhance the code as suggested.

**Comment by ZekerZhayard** [comment] 2021-03-11 09:18
The issue has been fixed by https://github.com/eclipse/openj9/pull/12148 and https://github.com/eclipse/openj9/pull/12164.
The first nightly build which applied the fix is https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2021-03-11-08-45.

**Comment by 3TUSK** [comment] 2021-03-12 00:40
@vectorwing A quick correction on my previous statement: apparently you cannot use `DeferredRegister` on `ConfiguredFeature<?, ?>`; you have to use vanilla `Registry.register` for `ConfiguredFeature`. @ZekerZhayard was correct on separating out the event listener to a new class because doing so avoids the accidental class initialization.

For regular `Feature`, `DeferredRegister` seems viable and should be preferred when possible.

An example may be found at here: https://github.com/MysticMods/Traverse/blob/1.16/src/main/java/epicsquid/traverse/init/ModFeatures.java  
Notice the empty `load()` method at the end of the class, which is for triggering class initialization; call it within a registry event.

**Comment by vectorwing** [comment] 2021-03-13 05:36
Finally got some time to look at this properly. 🤦‍♂️

OK, so I already use `DeferredRegister` for my `RiceCropFeature`, and seems I won't need to change the `ConfiguredFeature` registers. So just to make sure I understood it correctly: ideally, I should separate `onBiomeLoad` from `CropPatchGeneration` into its own class? Perhaps the usual `CommonEventHandler` I already use?

Also, good to know the surrounding OpenJ9 issues are resolved! 👍

**Comment by 3TUSK** [comment] 2021-03-13 22:47
> ideally, I should separate onBiomeLoad from CropPatchGeneration into its own class

That is correct.

**Comment by vectorwing** [comment] 2021-03-14 01:16
I pushed a branch with the proposed changes, after chatting a bunch on Discord as well. Gonna open a PR for it soon; to anyone here, feel free to look over it and review whether I understood what was meant here, as I'm a bit new to some of this. x)

**Closed as completed** 2021-03-14 16:53 UTC
Labels: enhancement
