### ISSUE TITLE
[MC Version]: 1.17.1

### ISSUE THREAD

**Issue by Snow5Wolf** [vectorwing/FarmersDelight#615] opened 2023-01-07 13:57 UTC
### Description

Datapack break world generation. I think it was farmer delight conflict with a mod because when i enter the game without farmer delight it work perfectly normal. Farmer delight also work normal without all other mods , it does work normaly with optifine too.

### Steps to reproduce

1. Download Farmer Delight along with some other mods and use it in 1.17.1 version
2. Try to create a world
3. Datapack broke

### Mod list

		notenoughcrashes-4.1.4+1.17.1-forge.jar           |Not Enough Crashes            |notenoughcrashes              |4.1.4+1.17.1        |DONE      |Manifest: NOSIGNATURE
		netherportalfix-8.0.0+0.jar                       |NetherPortalFix               |netherportalfix               |8.0.0+0             |DONE      |Manifest: NOSIGNATURE
		TRansliterationLib-forge-1.2.2-1.17.1.jar         |TRansliterationLib Mod        |transliterationlib            |1.2.2               |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v2.0.2-1.17.1-Forge.jar                 |Easy Magic                    |easymagic                     |2.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.17.1-8.3.1.62.jar                           |Just Enough Items             |jei                           |8.3.1.62            |DONE      |Manifest: NOSIGNATURE
		Nameless Trinkets-1.17.1-1.4.3.jar                |Nameless Trinkets             |nameless_trinkets             |1.17.1-1.4.3        |DONE      |Manifest: NOSIGNATURE
		Architects-Palette-1.17.1-1.0.0.jar               |Architect's Palette           |architects_palette            |1.1.2               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.17.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.17.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		minicoal-1.17.1-1.0.1.jar                         |MiniCoal                      |minicoal                      |1.17.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		hourglass-1.17.1-1.2.1.0.jar                      |Hourglass                     |hourglass                     |1.17.1-1.2.1.0      |DONE      |Manifest: NOSIGNATURE
		JRFTL [1.17.1]-1.3.jar                            |JRFTL                         |jrftl                         |1.3                 |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.17.1-8.0.11.jar               |Controlling                   |controlling                   |8.0.11              |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.17.1-5.0.0.1.jar                 |Comforts                      |comforts                      |1.17.1-5.0.0.1      |DONE      |Manifest: NOSIGNATURE
		citadel-1.9.5-1.17.1.jar                          |Citadel                       |citadel                       |1.9.5               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.14.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.14.1              |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.17.1-1.9.2-forge.jar             |Nature's Compass              |naturescompass                |1.17.1-1.9.2-forge  |DONE      |Manifest: NOSIGNATURE
		artifacts-1.17.1-3.0.2.jar                        |Artifacts                     |artifacts                     |1.17.1-3.0.2        |DONE      |Manifest: NOSIGNATURE
		configured-1.5.1-1.17.1.jar                       |Configured                    |configured                    |1.5.1               |DONE      |Manifest: NOSIGNATURE
		ItemBorders-1.17.1-1.1.5.jar                      |Item Borders                  |itemborders                   |1.1.5               |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.17.1-2.3.9.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.3.9               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.17.1-3.12.3.496.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.17.1-3.12.3.496   |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.17.1.1.3.4.jar                   |Guard Villagers               |guardvillagers                |1.3.4               |DONE      |Manifest: NOSIGNATURE
		forgivingvoid-5.0.0+0.jar                         |Forgiving Void                |forgivingvoid                 |5.0.0+0             |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.17.1-1.1.2-forge.jar           |Explorer's Compass            |explorerscompass              |1.17.1-1.1.2-forge  |DONE      |Manifest: NOSIGNATURE
		PickUpNotifier-v2.1.0-1.17.1-Forge.jar            |Pick Up Notifier              |pickupnotifier                |2.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		catalogue-1.5.0-1.17.1.jar                        |Catalogue                     |catalogue                     |1.5.0               |DONE      |Manifest: NOSIGNATURE
		balm-1.8.2+0.jar                                  |Balm                          |balm                          |1.8.2+0             |DONE      |Manifest: NOSIGNATURE
		FpsReducer-forge-1.24-mc1.17.1.jar                |FPS Reducer                   |fpsreducer                    |1.24-mc1.17.1       |DONE      |Manifest: NOSIGNATURE
		randomium-1.17-1.8.jar                            |Randomium                     |randomium                     |1.17.1-1.8          |DONE      |Manifest: NOSIGNATURE
		wandering-bag-1.17.1-1.0.3.jar                    |Wandering Bag                 |wandering_bag                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		cloth-config-5.3.63-forge.jar                     |Cloth Config v4 API           |cloth_config                  |5.3.63              |DONE      |Manifest: NOSIGNATURE
		forge-1.17.1-37.1.1-universal.jar                 |Forge                         |forge                         |37.1.1              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		stackrefill_1.17.1-2.0.jar                        |Stack Refill                  |stackrefill                   |2.0                 |DONE      |Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.17-1.5.0.jar                       |MmmMmmMmmMmm                  |dummmmmmy                     |1.17-1.5.0          |DONE      |Manifest: NOSIGNATURE
		scuba_gear-1.17.1-1.0.3.jar                       |Scuba Gear                    |scuba_gear                    |1.0.3               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.17.1-1.0.4.jar                  |Supplementaries               |supplementaries               |1.0.1               |DONE      |Manifest: NOSIGNATURE
		Buddycards-1.17.1-2.7.2.jar                       |Buddycards                    |buddycards                    |1.17.1-2.7.2        |DONE      |Manifest: NOSIGNATURE
		upgradednetherite-1.17.1-3.0.0.3-release.jar      |Upgraded Netherite            |upgradednetherite             |1.17.1-3.0.0.3-relea|DONE      |Manifest: NOSIGNATURE
		selene-1.17.1-1.11.jar                            |Selene                        |selene                        |1.17.1-1.11.0       |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.17.1-1.4.2.jar               |Advancement Plaques           |advancementplaques            |1.4.2               |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-13.0.0+0.jar                       |CraftingTweaks                |craftingtweaks                |13.0.0+0            |DONE      |Manifest: NOSIGNATURE
		alltheores-1.5.3-1.17.1-37.0.104.jar              |AllTheOres                    |alltheores                    |1.5.3-1.17.1-37.0.10|DONE      |Manifest: NOSIGNATURE
		client-1.17.1-20210706.113038-srg.jar             |Minecraft                     |minecraft                     |1.17.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EnchantmentDescriptions-Forge-1.17.1-8.17.3.jar   |EnchantmentDescriptions       |enchdesc                      |8.17.3              |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.17-4.0.2.jar                        |The One Probe                 |theoneprobe                   |1.17-4.0.2          |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.17.1-1.6.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.17.1-1.6.0        |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.17.1-2.15.jar               |Mouse Tweaks                  |mousetweaks                   |2.15                |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.17.1-1.17.3.jar                        |Tool Belt                     |toolbelt                      |1.17.3              |DONE      |Manifest: NOSIGNATURE
		Highlighter-1.17.1-1.1.1.jar                      |Highlighter                   |highlighter                   |1.1.1               |DONE      |Manifest: NOSIGNATURE
		frosted-friends-1.17.1-1.0.6.jar                  |Frosted Friends               |frosted_friends               |1.0.7               |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-1.3.3.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.3.3               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.17.1-1.0.27.jar                         |Iceberg                       |iceberg                       |1.0.27              |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.17.1-5.0.2.7.jar                   |Curios API                    |curios                        |1.17.1-5.0.2.7      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.17.1-57.jar                           |Patchouli                     |patchouli                     |1.17.1-57           |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.17.1-1.1.5.jar                |Legendary Tooltips            |legendarytooltips             |1.1.5}              |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.17.0_Forge_1.17.1.jar           |Xaero's Minimap               |xaerominimap                  |22.17.0             |DONE      |Manifest: NOSIGNATURE
		ironchests-1.0.jar                                |Ironchests                    |ironchests                    |1.0                 |DONE      |Manifest: NOSIGNATURE
		collective-1.17.1-4.25.jar                        |Collective                    |collective                    |4.25                |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.17.1-0.33.jar                   |Polymorph                     |polymorph                     |1.17.1-0.33         |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.9.158.jar                         |OreExcavation                 |oreexcavation                 |1.9.158             |DONE      |Manifest: NOSIGNATURE
		EarthMobs-1.17.1-0.4.2.jar                        |Earth Mobs Mod                |earthmobsmod                  |1.17.1-0.4.2        |DONE      |Manifest: NOSIGNATURE
		villagertools-1.17.1-1.0.2.jar                    |villagertools                 |villagertools                 |1.17.1-1.0.2        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		BetterThirdPerson-Forge-1.17.1-1.5.2.jar          |Better Third Person           |betterthirdperson             |1.5.2               |DONE      |Manifest: NOSIGNATURE
		InventoryHud_[1.17.1].forge-3.4.1.jar             |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.1               |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.17.1-2.5.8.jar                    |Gobber 2                      |gobber2                       |2.5.8               |DONE      |Manifest: NOSIGNATURE
		upgradedcore-1.17.1-2.0.0.0-release.jar           |Upgraded Core                 |upgradedcore                  |1.17.1-2.0.0.0-relea|DONE      |Manifest: NOSIGNATURE
		starterkit_1.17.1-3.1.jar                         |Starter Kit                   |starterkit                    |3.1                 |DONE      |Manifest: NOSIGNATURE
		architectury-2.10.12.jar                          |Architectury                  |architectury                  |2.10.12             |DONE      |Manifest: NOSIGNATURE
		snad-1.1.1-1.17.jar                               |Snad                          |snad                          |1.1.1               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.17.1-2.4.0.jar                |AppleSkin                     |appleskin                     |2.4.0+mc1.17.1      |DONE      |Manifest: NOSIGNATURE
		Chimes-1.1.2-1.17.1.jar                           |Chimes                        |chimes                        |1.1.2               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v2.0.2-1.17.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |2.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		allthetweaks-1.6.0-1.17.1-37.0.36.jar             |All The Tweaks                |allthetweaks                  |1.6.0-1.17.1-37.0.36|DONE      |Manifest: NOSIGNATURE
		BetterF3-2.0.0-Forge-1.17.1.jar                   |BetterF3                      |betterf3                      |2.0.0               |DONE      |Manifest: NOSIGNATURE
		FriendlyFire-1.17.1-8.0.3.jar                     |FriendlyFire                  |friendlyfire                  |8.0.3               |DONE      |Manifest: NOSIGNATURE
		AdvancedCompas-forge-1.17.1-1.2.11.jar            |Advanced Compass              |advancedcompass               |1.2.11              |DONE      |Manifest: NOSIGNATURE
		expandability-4.0.2-forge.jar                     |ExpandAbility                 |expandability                 |4.0.2               |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-1.17.1-0.3.0.jar                   |Valhelsia Core                |valhelsia_core                |1.17.1-0.3.0        |DONE      |Manifest: NOSIGNATURE
		valhelsia_structures-1.17.1-0.1.1.jar             |Valhelsia Structures          |valhelsia_structures          |1.17.1-0.1.1        |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-1.17.1-2.0.0.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.17.1-2.0.0        |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v2.0.0-1.17.1-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |2.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		healingcampfire_1.17.1-3.3.jar                    |Healing Campfire              |healingcampfire               |3.3                 |DONE      |Manifest: NOSIGNATURE
		TradingPost-v2.0.0-1.17.1-Forge.jar               |Trading Post                  |tradingpost                   |2.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterAdvancements-1.17.1-0.1.2.116.jar 
		FarmerDelight 1.0.2(no extra info because i cannot create the world with it in the mods folder)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment] 2023-06-23 20:49
@Snow5Wolf, sorry for the very late reply! Although I'm no longer updating 1.17, I can take a look at the logs to see if I can identify the cause. Are you still having this issue?

Please provide your game logs here (latest.log, for example) after attempting your steps above.

**Comment by vectorwing** [comment] 2023-07-09 19:40
I'm closing this issue for now. If it's still happening, feel free to reply with the info requested above.

**Closed as completed by vectorwing** 2023-07-09 19:40 UTC
