### ISSUE TITLE
[Bug] FORGE 1.18.1 Rice Crash

### ISSUE THREAD

**Issue by LivingLandmine** [vectorwing/FarmersDelight#407] opened 2022-01-29 01:43 UTC
**Description**
Planting rice crashes my game.

**Steps to reproduce:**

1. Acquire raw rice 
2. Plant raw rice.
3. Crash occurs.

**Logs**
[crash-2022-01-28_20.21.55-server.txt](https://github.com/vectorwing/FarmersDelight/files/7962738/crash-2022-01-28_20.21.55-server.txt)

**Mod list:**
|Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.1-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.1-1.0.1.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.18-forge-5.2.3.jar                         |Kiwi                          |kiwi                          |5.2.3               |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.1-1.8.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.1-1.8.0        |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v5.0.4_mc1.18.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		Companion-1.18-forge-1.1.1.jar                    |Companion                     |companion                     |1.1.1               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.4.1_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.4-mc1.18.1.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.4               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.2-mc1.18.1.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.1-2.4.0.jar                     |Doggy Talents 2               |doggytalents                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.2-mc1.18.1.jar                    |Macaw's Windows               |mcwwindows                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18-3.0.0.1.jar                     |Caelus API                    |caelus                        |1.18-3.0.0.1        |DONE      |Manifest: NOSIGNATURE
		torohealth-1.18-forge-2.jar                       |ToroHealth                    |torohealth                    |1.18-forge-2        |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.4.0-mc1.18.jar        |NotEnoughAnimations Mod       |notenoughanimations           |1.4.0               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.5.1.jar                     |Flywheel                      |flywheel                      |1.18-0.5.1          |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.5.1.jar                   |Curios API                    |curios                        |1.18.1-5.0.5.1      |DONE      |Manifest: NOSIGNATURE
		tetra-1.18.1-4.3.0.jar                            |Tetra                         |tetra                         |4.3.0               |DONE      |Manifest: NOSIGNATURE
		mutil-1.18.1-4.1.0.jar                            |mutil                         |mutil                         |4.1.0               |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4c.jar                         |Create                        |create                        |0.4c                |DONE      |Manifest: NOSIGNATURE
		corail_woodcutter-1.18-2.2.1.jar                  |Corail Woodcutter             |corail_woodcutter             |2.2.1               |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.18.1-1.2.4.jar                    |Falling Leaves                |fallingleaves                 |1.2.4               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.1-0.35.jar                   |Polymorph                     |polymorph                     |1.18.1-0.35         |DONE      |Manifest: NOSIGNATURE
		citadel-1.10.8-1.18.jar                           |Citadel                       |citadel                       |1.10.8              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.16.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.16.0              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18-1.6.0.jar            |Better Third Person           |betterthirdperson             |1.6.0               |DONE      |Manifest: NOSIGNATURE
		tombstone-7.3.3-1.18.jar                          |Corail Tombstone              |tombstone                     |7.3.3               |DONE      |Manifest: NOSIGNATURE
		curioofundying-forge-1.18-5.3.0.0.jar             |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.5-mc1.18.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		curiouselytra-forge-1.18.1-5.0.1.0.jar            |Curious Elytra                |curiouselytra                 |1.18.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE
		PickUpNotifier-v3.1.0-1.18.1-Forge.jar            |Pick Up Notifier              |pickupnotifier                |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		balm-2.4.0+0.jar                                  |Balm                          |balm                          |2.4.0+0             |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.1.3-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.1.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		3dSkinLayers-forge-mc1.18-1.3.1.jar               |3dSkinLayers                  |skinlayers3d                  |1.3.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.19-universal.jar                |Forge                         |forge                         |39.0.19             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.18.1-2.3.2.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.2        |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		supplementaries-1.18.1-1.1.8.jar                  |Supplementaries               |supplementaries               |1.1.7               |DONE      |Manifest: NOSIGNATURE
		nutritionalbalance-1.18-3.0.0.jar                 |Nutritional Balance           |nutritionalbalance            |1.18-3.0.0          |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.11.jar                              |Selene                        |selene                        |1.18-1.11.0         |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: GL33 Instanced Arrays

**Comment by vectorwing** [comment] 2022-01-29 01:53
Duplicate of issue #379.

Please update your FD to the latest version, and Forge to 39.0.45 or above.

**Closed as completed by vectorwing** 2022-01-29 01:53 UTC
