### ISSUE TITLE
[1.18.1] Freeze when attempting to plant rice on an invalid block

### ISSUE THREAD

**Issue by Mithrik** [vectorwing/FarmersDelight#397] opened 2022-01-24 03:10 UTC
**Description**
Exactly as the title says. I've stumbled upon this issue a couple times already when planting rice. If the block where the rice is being planted does not fulfill the planting requirements, the game freezes.

**Steps to reproduce:**
Try to plant rice out of water or on top of a non-solid block.

**Expected behavior:**
Rice should not be planted and the game continues to work as intended.

**Logs**
Here's the exception from the logs.

[19:40:30] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: DIRT
	at vectorwing.farmersdelight.common.item.RiceItem.m_6225_(RiceItem.java:27) ~[FarmersDelight-1.18.1-1.0.1.jar%2359!:1.18.1-1.0.1]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:583) ~[forge-1.18.1-39.0.20-universal.jar%2372!:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%2368!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Mod list:**
Mod List: 
- Farmer's Delight 1.0.1
- Forge 39.0.20

I don't think my other mods are relevant, but just in case of, I'm also using Minecolonies (with its dependencies) and Serene Seasons.

**Comment by vectorwing** [comment] 2022-01-24 04:19
Duplicate of issue #379. Your Forge and FD versions are fairly outdated; please update to **FD 1.0.3** and **Forge 39.0.45** or above.

**Closed as completed by vectorwing** 2022-01-24 04:19 UTC
