### ISSUE TITLE
[1.16.5] Pigs and Hoglins not dropping ham when killed with knife.

### ISSUE THREAD

**Issue by Karso12** [vectorwing/FarmersDelight#254] opened 2021-04-10 19:11 UTC
**Description**
Ham not dropping from Hoglins nor Pigs when killed with knives in multiplayer. Works just fine in singleplayer. 
 
**Steps to reproduce:**
Kill pigs or hoglings with a knife in multiplayer

**Expected behavior:**
Hoglins and pigs dropping ham when killed with a knife

**Logs**
https://pastebin.com/y2Sa3m7U

**Mod list:**

forge-1.16.5-36.1.3-client.jar               
FarmersDelight-1.16.3-0.4.0.jar            
voicechat-1.16.5-1.1.4.jar                      
obfuscate-0.6.0-1.16.3.jar                      
DungeonCrawl-1.16.3-2.2.4.jar 
buildersaddition-1.16.4-20210214a.jar 
worldedit-forge-mc1.16.3-7.2.2-dist.jar 
gemspork-1.16.4-1.5.0.jar 
furniture-7.0.0-pre19-1.16.3.jar
dungeons_plus-1.16.4-1.1.3.jar    
jei-1.16.5-7.6.1.75.jar                     
enhancedcelestials-1.0.2-1.16.4.jar 
goblintraders-1.3.1-1.16.3.jar 
forge-1.16.5-36.1.3-universal.jar  
exoticbirds-1.16.4-1.1.0.jar   
Space-Bosstools-1.16.5-4.7.jar  
gemspark-1.16.4-1.2.3.0.jar 
create-mc1.16.5_v0.3.1.jar   
chiselsandbits-0.3.4-RELEASE.jar 
Xaeros_Minimap_21.4.5_Forge_1.16.5.jar
camera-1.16.5-1.0.2.jar    
structure_gel-1.16.4-1.7.5.jar
citadel-1.6.2.jar  
alexsmobs-1.8.1.jar
rats-7.1.1-1.16.5.jar

**Comment by vectorwing** [comment] 2021-04-10 19:27
Tested this on a local SMP combo with only FD (server and client on 0.4.0) and it worked as intended, with both mobs dropping ham at their corresponding ratios. Not sure if it would differ on a non-local server, but it shouldn't.

![image](https://user-images.githubusercontent.com/5566692/114282248-22954580-9a19-11eb-8dae-b26f69044861.png)

There's a chance some other mod might be messing with loot table injections. If you can, try the following:
- Check if the knife you're using belongs to Farmer's Delight (curved blade);
- Host a "minimal instance" server with only FD (and JEI if you want), and see if the issue persists.

**Comment by vectorwing** [comment] 2021-04-10 19:30
Also, do you have access to server logs? Those might contain more info, if the injection is indeed failing.

**Comment by Karso12** [comment] 2021-04-10 19:30
Server owner would be online tomorrow, I'll see what I can do.

**Comment by vectorwing** [comment] 2021-04-11 02:31
Just tested with the datapack you mentioned on Discord, and it turns out to be the cause of the issue.
https://vanillatweaks.net/picker/datapacks/

Datapacks like these tend to override loot injections, which is what FD uses to allow knives to scavenge more drops. It's only failing in multiplayer because your server has it installed.

This can be "fixed" on my end if I migrate the knife drops to Global Loot Modifiers, but that is a delicate system; the migration would take some time. On the server's end, the datapack would have to be extensively modified, which isn't viable.

I'll keep this in the backlog. 👍

**Comment by Karso12** [comment] 2021-04-11 10:54
Thank you so much!

**Comment by vectorwing** [comment] 2021-04-18 19:06
Oops, I reopened the wrong issue. lol
I'm going to migrate the knife scavenging mechanic to Global Loot Modifiers, which should (hopefully) fix this issue and be less fragile overall.

**Comment by vectorwing** [comment] 2021-05-03 05:45
0.4.2 has introduced a fix for this issue. 👍

**Closed as completed by vectorwing** 2021-05-03 05:45 UTC
Labels: enhancement
