### ISSUE TITLE
Cooking Pot should re-use bowls

### ISSUE THREAD

**Issue by Nightcaste** [vectorwing/FarmersDelight#123] opened 2021-01-13 01:34 UTC
I'm not sure how to describe this, so bear with me.

As an example, Fish Stew requires a fish, an onion, tomato sauce, and a bowl to serve it in.  Tomato sauce requires two tomatoes and a bowl to serve it in.  The tomato sauce bowl just ceases to exist when you use it to make the fish stew.

Since the tomato sauce requires a bowl, the fish stew should not require a second bowl, because there's already a bowl in there.  This should go for any recursive cooking pot recipes.

**Comment by vectorwing** [comment] 2021-01-13 01:41
The bowl does not vanish; it is ejected from the top of the Cooking Pot.

The Cooking Pot will throw leftover ingredient containers from its top side, against the spoon's direction. The throw is high enough to clear a Hopper above and to the side of the pot, allowing you to re-insert the bowl directly on the container slot, or store it away in a Basket, for example.

If the bowl actually did vanish instead of being thrown out, then it's an issue. In such case, I'll need the FD and Forge versions you're using.

**Comment by vectorwing** [comment] 2021-01-17 22:18
I'll be closing the issue for now. If the behavior described above isn't working as intended, feel free to reopen. 👍

**Closed as completed by vectorwing** 2021-01-17 22:18 UTC

**Comment by Nightcaste** [comment] 2021-01-18 23:00
Sorry for taking so long to reply.  I have verified that it does behave the way you said.  I have an item collector that grabbed them, so it seemed like they were disappearing.
